# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""FFI APIs for tvm.runtime"""
# tvm-ffi-stubgen(begin): import-section
# fmt: off
# isort: off
from __future__ import annotations
from tvm_ffi import init_ffi_api as _FFI_INIT_FUNC
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence
    from ctypes import c_void_p
    from tvm_ffi import Device, Module, Shape, Tensor, dtype
    from typing import Any, Callable
# isort: on
# fmt: on
# tvm-ffi-stubgen(end)


# Exports functions registered in runtime namespace.
# tvm-ffi-stubgen(begin): global/runtime
# fmt: off
_FFI_INIT_FUNC("runtime", __name__)
if TYPE_CHECKING:
    def CSourceModuleCreate(_0: str, _1: str, _2: Sequence[str] | None, _3: Sequence[str] | None, /) -> Module: ...
    def Device_SetStream(_0: Device, _1: int, /) -> None: ...
    def Device_StreamCreate(_0: Device, /) -> int: ...
    def Device_StreamFree(_0: Device, _1: int, /) -> None: ...
    def Device_StreamSync(_0: Device, _1: int, /) -> None: ...
    def Device_StreamSyncFromTo(_0: Device, _1: int, _2: int, /) -> None: ...
    def GetCudaDeviceCount() -> int: ...
    def GetCudaFreeMemory() -> str: ...
    def GetDeviceAttr(*args: Any) -> Any: ...
    def LoadParams(_0: bytes, /) -> Mapping[str, Tensor]: ...
    def LoadParamsFromFile(_0: str, /) -> Mapping[str, Tensor]: ...
    def ModuleImportsBlobName() -> str: ...
    def ModuleLoadStaticLibrary(_0: str, _1: Sequence[str], /) -> Module: ...
    def ModulePackImportsToC(_0: Module, _1: bool, _2: str, /) -> str: ...
    def ModulePackImportsToLLVM(_0: Module, _1: bool, _2: str, _3: str, /) -> Module: ...
    def ModulePackImportsToTensor(_0: Module, /) -> Tensor: ...
    def NumThreads() -> int: ...
    def RPCTimeEvaluator(_0: Module | None, _1: str, _2: int, _3: int, _4: int, _5: int, _6: int, _7: int, _8: int, _9: int, _10: int, _11: str, /) -> Callable[..., Any]: ...
    def RuntimeEnabled(_0: str, /) -> bool: ...
    def SaveParams(_0: Mapping[str, Tensor], /) -> bytes: ...
    def SaveParamsToFile(_0: Mapping[str, Tensor], _1: str, /) -> None: ...
    def SourceModuleCreate(_0: str, _1: str, /) -> Module: ...
    def TVMSetStream(_0: int, _1: int, _2: c_void_p, /) -> None: ...
    def TVMTensorAllocWithScope(_0: Shape, _1: dtype, _2: Device, _3: str | None, /) -> Tensor: ...
    def TVMTensorCopyFromBytes(_0: Tensor, _1: c_void_p, _2: int, /) -> None: ...
    def TVMTensorCopyFromTo(_0: Tensor, _1: Tensor, /) -> None: ...
    def TVMTensorCopyToBytes(_0: Tensor, _1: c_void_p, _2: int, /) -> None: ...
    def TVMTensorCreateView(_0: Tensor, _1: Shape, _2: dtype, _3: int, /) -> Tensor: ...
    def _datatype_get_type_registered(*args: Any) -> Any: ...
    def config_threadpool(*args: Any) -> Any: ...
    def cuTensorMapEncodeTiled(*args: Any) -> Any: ...
    def get_cuda_stream() -> c_void_p: ...
# fmt: on
# tvm-ffi-stubgen(end)
