# TCL File Generated by Component Editor 18.0
# Wed Jan 23 11:17:14 HKT 2019
# DO NOT MODIFY


# 
# store "store" v1.0
#  2019.01.23.11:17:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module store
# 
set_module_property DESCRIPTION ""
set_module_property NAME store
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Chisel
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME store
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Store
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file store.v VERILOG PATH store.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file store.v VERILOG PATH store.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point out_mem
# 
add_interface out_mem avalon start
set_interface_property out_mem addressUnits SYMBOLS
set_interface_property out_mem associatedClock clock
set_interface_property out_mem associatedReset reset
set_interface_property out_mem bitsPerSymbol 8
set_interface_property out_mem burstOnBurstBoundariesOnly false
set_interface_property out_mem burstcountUnits WORDS
set_interface_property out_mem doStreamReads false
set_interface_property out_mem doStreamWrites false
set_interface_property out_mem holdTime 0
set_interface_property out_mem linewrapBursts false
set_interface_property out_mem maximumPendingReadTransactions 0
set_interface_property out_mem maximumPendingWriteTransactions 0
set_interface_property out_mem readLatency 0
set_interface_property out_mem readWaitTime 1
set_interface_property out_mem setupTime 0
set_interface_property out_mem timingUnits Cycles
set_interface_property out_mem writeWaitTime 0
set_interface_property out_mem ENABLED true
set_interface_property out_mem EXPORT_OF ""
set_interface_property out_mem PORT_NAME_MAP ""
set_interface_property out_mem CMSIS_SVD_VARIABLES ""
set_interface_property out_mem SVD_ADDRESS_GROUP ""

add_interface_port out_mem io_out_mem_address address Output 17
add_interface_port out_mem io_out_mem_read read Output 1
add_interface_port out_mem io_out_mem_readdata readdata Input 128
add_interface_port out_mem io_out_mem_waitrequest waitrequest Input 1


# 
# connection point s2g_dep_queue
# 
add_interface s2g_dep_queue avalon_streaming start
set_interface_property s2g_dep_queue associatedClock clock
set_interface_property s2g_dep_queue associatedReset reset
set_interface_property s2g_dep_queue dataBitsPerSymbol 1
set_interface_property s2g_dep_queue errorDescriptor ""
set_interface_property s2g_dep_queue firstSymbolInHighOrderBits false
set_interface_property s2g_dep_queue maxChannel 0
set_interface_property s2g_dep_queue readyLatency 0
set_interface_property s2g_dep_queue ENABLED true
set_interface_property s2g_dep_queue EXPORT_OF ""
set_interface_property s2g_dep_queue PORT_NAME_MAP ""
set_interface_property s2g_dep_queue CMSIS_SVD_VARIABLES ""
set_interface_property s2g_dep_queue SVD_ADDRESS_GROUP ""

add_interface_port s2g_dep_queue io_s2g_dep_queue_data data Output 8
add_interface_port s2g_dep_queue io_s2g_dep_queue_ready ready Input 1
add_interface_port s2g_dep_queue io_s2g_dep_queue_valid valid Output 1


# 
# connection point outputs
# 
add_interface outputs avalon start
set_interface_property outputs addressUnits SYMBOLS
set_interface_property outputs associatedClock clock
set_interface_property outputs associatedReset reset
set_interface_property outputs bitsPerSymbol 8
set_interface_property outputs burstOnBurstBoundariesOnly false
set_interface_property outputs burstcountUnits WORDS
set_interface_property outputs doStreamReads false
set_interface_property outputs doStreamWrites false
set_interface_property outputs holdTime 0
set_interface_property outputs linewrapBursts false
set_interface_property outputs maximumPendingReadTransactions 0
set_interface_property outputs maximumPendingWriteTransactions 0
set_interface_property outputs readLatency 0
set_interface_property outputs readWaitTime 1
set_interface_property outputs setupTime 0
set_interface_property outputs timingUnits Cycles
set_interface_property outputs writeWaitTime 0
set_interface_property outputs ENABLED true
set_interface_property outputs EXPORT_OF ""
set_interface_property outputs PORT_NAME_MAP ""
set_interface_property outputs CMSIS_SVD_VARIABLES ""
set_interface_property outputs SVD_ADDRESS_GROUP ""

add_interface_port outputs io_outputs_address address Output 32
add_interface_port outputs io_outputs_write write Output 1
add_interface_port outputs io_outputs_writedata writedata Output 128
add_interface_port outputs io_outputs_waitrequest waitrequest Input 1


# 
# connection point g2s_dep_queue
# 
add_interface g2s_dep_queue avalon_streaming end
set_interface_property g2s_dep_queue associatedClock clock
set_interface_property g2s_dep_queue associatedReset reset
set_interface_property g2s_dep_queue dataBitsPerSymbol 1
set_interface_property g2s_dep_queue errorDescriptor ""
set_interface_property g2s_dep_queue firstSymbolInHighOrderBits false
set_interface_property g2s_dep_queue maxChannel 0
set_interface_property g2s_dep_queue readyLatency 0
set_interface_property g2s_dep_queue ENABLED true
set_interface_property g2s_dep_queue EXPORT_OF ""
set_interface_property g2s_dep_queue PORT_NAME_MAP ""
set_interface_property g2s_dep_queue CMSIS_SVD_VARIABLES ""
set_interface_property g2s_dep_queue SVD_ADDRESS_GROUP ""

add_interface_port g2s_dep_queue io_g2s_dep_queue_data data Input 8
add_interface_port g2s_dep_queue io_g2s_dep_queue_ready ready Output 1
add_interface_port g2s_dep_queue io_g2s_dep_queue_valid valid Input 1


# 
# connection point store_queue
# 
add_interface store_queue avalon_streaming end
set_interface_property store_queue associatedClock clock
set_interface_property store_queue associatedReset reset
set_interface_property store_queue dataBitsPerSymbol 128
set_interface_property store_queue errorDescriptor ""
set_interface_property store_queue firstSymbolInHighOrderBits false
set_interface_property store_queue maxChannel 0
set_interface_property store_queue readyLatency 0
set_interface_property store_queue ENABLED true
set_interface_property store_queue EXPORT_OF ""
set_interface_property store_queue PORT_NAME_MAP ""
set_interface_property store_queue CMSIS_SVD_VARIABLES ""
set_interface_property store_queue SVD_ADDRESS_GROUP ""

add_interface_port store_queue io_store_queue_data data Input 128
add_interface_port store_queue io_store_queue_ready ready Output 1
add_interface_port store_queue io_store_queue_valid valid Input 1

