# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# pylint: disable=invalid-name, missing-docstring
"""Unittests for tvm.tirx.script.ir_builder"""

import tvm
import tvm.runtime
import tvm.testing
from tvm import tirx
from tvm.ir.base import assert_structural_equal
from tvm.script.ir_builder import IRBuilder
from tvm.tirx.script import ir_builder as T


def test_ir_builder_tir_for():
    with IRBuilder() as ib:
        with T.serial(128) as a:
            with T.parallel(64) as b:
                with T.vectorized(32) as c:
                    with T.unroll(16) as d:
                        with T.thread_binding(8, thread="threadIdx.x") as e:
                            T.evaluate(0)

    # the for generated by IRBuilder
    for_actual = ib.get()

    # the expected for
    thread_binding_expected = tirx.For(
        loop_var=tirx.Var("", "int32"),
        min=0,
        extent=8,
        kind=tirx.ForKind.THREAD_BINDING,
        body=tirx.Evaluate(0),
        thread_binding=tirx.IterVar(
            None, tirx.Var("", "int32"), tirx.IterVar.ThreadIndex, "threadIdx.x"
        ),
    )
    unroll_expected = tirx.For(
        loop_var=tirx.Var("", "int32"),
        min=0,
        extent=16,
        kind=tirx.ForKind.UNROLLED,
        body=thread_binding_expected,
    )
    vectorized_expected = tirx.For(
        loop_var=tirx.Var("", "int32"),
        min=0,
        extent=32,
        kind=tirx.ForKind.VECTORIZED,
        body=unroll_expected,
    )
    parallel_expected = tirx.For(
        loop_var=tirx.Var("", "int32"),
        min=0,
        extent=64,
        kind=tirx.ForKind.PARALLEL,
        body=vectorized_expected,
    )
    for_expected = tirx.For(
        loop_var=tirx.Var("", "int32"),
        min=0,
        extent=128,
        kind=tirx.ForKind.SERIAL,
        body=parallel_expected,
    )

    # Check if the generated ir is expected
    assert_structural_equal(for_actual, for_expected, map_free_vars=True)


def test_ir_builder_tir_for_uint():
    with IRBuilder() as ib:
        with T.serial(tirx.const(128, "uint32")) as a:
            T.evaluate(0)

    # the for generated by IRBuilder
    for_actual = ib.get()

    for_expected = tirx.For(
        loop_var=tirx.Var("", "uint32"),
        min=tirx.const(0, "uint32"),
        extent=tirx.const(128, "uint32"),
        kind=tirx.ForKind.SERIAL,
        body=tirx.Evaluate(0),
    )

    # Check if the generated ir is expected
    assert_structural_equal(for_actual, for_expected, map_free_vars=True)


def test_ir_builder_tir_assert():
    with IRBuilder() as ib:
        with T.prim_func():
            T.assert_(T.int32() == 0, message="a is 0")
            T.evaluate(T.call_extern("int32", "after_assert"))
    # the assert generated by IRBuilder
    assert_actual = ib.get().body

    # AssertStmt is a leaf. The frame emits the assert and then the body stmts as siblings.
    assert_expected = tirx.SeqStmt(
        [
            tirx.AssertStmt(
                T.int32() == 0,
                tvm.ir.StringImm("RuntimeError"),
                [tvm.ir.StringImm("a is 0")],
            ),
            tirx.Evaluate(tirx.call_extern("int32", "after_assert")),
        ]
    )

    # Check if the generated ir is expected
    assert_structural_equal(assert_actual, assert_expected, map_free_vars=True)


def test_ir_builder_tir_bind():
    # Test that T.bind emits a flat Bind statement and returns the Var.
    with IRBuilder() as ib:
        v = T.bind(tirx.IntImm("int32", 2))
    # the let binding generated by IRBuilder
    let_actual = ib.get()

    # Bind is now flat (no body), so a single Bind stmt is emitted.
    let_expected = tirx.Bind(T.int32(), tirx.IntImm("int32", 2))

    # Check if the generated ir is expected
    assert_structural_equal(let_actual, let_expected, map_free_vars=True)
    # Check that the returned value is a Var
    assert isinstance(v, tirx.Var)


def test_ir_builder_tir_while():
    with IRBuilder() as ib:
        with T.while_(T.int32() > 0):
            T.evaluate(0)

    # the while generated by IRBuilder
    ir_actual = ib.get()

    # the expected while
    ir_expected = tirx.While(tirx.Var("x", "int32") > 0, tirx.Evaluate(0))

    # Check if the generated ir is expected
    assert_structural_equal(ir_actual, ir_expected, map_free_vars=True)


def test_ir_builder_tir_if_then_else():
    with IRBuilder() as ib:
        with T.if_(T.int32() < 12):
            with T.then_():
                T.evaluate(T.int32(0))
            with T.else_():
                T.evaluate(T.int32(1))

    # the if_then_else generated by IRBuilder
    ir_actual = ib.get()

    # the expected if_then_else
    ir_expected = tirx.IfThenElse(
        tirx.Var("c", "int32") < 12,
        tirx.Evaluate(tirx.IntImm("int32", 0)),
        tirx.Evaluate(tirx.IntImm("int32", 1)),
    )

    # Check if the generated ir is expected
    assert_structural_equal(ir_actual, ir_expected, map_free_vars=True)


def test_ir_builder_tir_buffer_store():
    buffer_a = T.Buffer((10, 10), "float32")
    i = T.int32()
    with IRBuilder() as ib:
        T.buffer_store(buffer_a, 0.1, [0, i])

    # the buffer store generated by IRBuilder
    ir_actual = ib.get()

    # the expected buffer store
    ir_expected = tirx.BufferStore(buffer_a, 0.1, [0, i])

    # Check if the generated ir is expected
    assert_structural_equal(ir_actual, ir_expected, map_free_vars=True)


def test_ir_builder_tir_buffer_store_scalable_vec():
    buffer_a = T.Buffer((30,), "float32")
    value = T.broadcast(0.11, 4 * tvm.tirx.vscale())
    index = T.ramp(0, 1, 4 * tvm.tirx.vscale())

    with IRBuilder() as ib:
        T.buffer_store(buffer_a, value, [index])

    # the buffer store generated by IRBuilder
    ir_actual = ib.get()

    # the expected buffer store
    ir_expected = tirx.BufferStore(buffer_a, value, [index])

    # Check if the generated ir is expected
    assert_structural_equal(ir_actual, ir_expected, map_free_vars=True)


def test_ir_builder_tir_evaluate():
    with IRBuilder() as ib:
        T.evaluate(0)
    # the evaluate generated by IRBuilder
    eval_actual = ib.get()

    # the expected evaluate
    eval_expected = tirx.Evaluate(0)

    # Check if the generated ir is expected
    assert_structural_equal(eval_actual, eval_expected, map_free_vars=True)


def test_ir_builder_tir_inline():
    with IRBuilder() as ib:
        m, n = T.meta_var(1), T.meta_var(2)
        a, b = T.meta_var([3, 4])
        T.evaluate(m + n + a + b)
    # the evaluate generated by IRBuilder
    eval_actual = ib.get()

    # the expected evaluate
    eval_expected = tirx.Evaluate(10)

    # Check if the generated ir is expected
    assert_structural_equal(eval_actual, eval_expected, map_free_vars=True)


if __name__ == "__main__":
    tvm.testing.main()
