FROM ubuntu:18.04

ENV http_proxy $HTTP_PROXY
ENV https_proxy $HTTPS_PROXY

# 1. Prepare dependence.
RUN apt-get update && apt-get install -y wget git vim python3 python3-dev python3-setuptools gcc libtinfo-dev zlib1g-dev build-essential cmake libedit-dev libxml2-dev
RUN echo deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main\
     >> /etc/apt/sources.list.d/llvm.list
RUN echo deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main\
     >> /etc/apt/sources.list.d/llvm.list
RUN echo deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main\
     >> /etc/apt/sources.list.d/llvm.list
RUN echo deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic main\
     >> /etc/apt/sources.list.d/llvm.list
RUN wget -q -O - http://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -
RUN apt-get update && apt-get install -y llvm-9 clang-9 libclang-9-dev

# 2. Install TVM
WORKDIR /workspace/
RUN git clone --recursive https://github.com/apache/tvm tvm
WORKDIR /workspace/tvm/
RUN mkdir build && cp cmake/config.cmake build
RUN cd build && echo set\(USE_LLVM llvm-config-9\) >> config.cmake && cmake .. && make -j4

# 3. Prepare Python sitpackage
RUN apt-get install -y python3-pip && pip3 install --upgrade pip
RUN pip3 install numpy scipy decorator attrs tornado psutil tensorflow pytest

# 4. Init
WORKDIR /workspace/tvm/
ENV TVM_HOME=/workspace/tvm
ENV PYTHONPATH=$TVM_HOME/python:${PYTHONPATH}

# 6. Run test code
ADD ./inference_x86_test.py /workspace/
# RUN python3 /workspace/inference_x86_test.py
