# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

github:
  description: "Open deep learning compiler stack for cpu, gpu and specialized accelerators"
  homepage: https://tvm.apache.org/
  labels:
    - tvm
    - compiler
    - tensor
    - deep-learning
    - gpu
    - opencl
    - metal
    - performance
    - javascript
    - rocm
    - vulkan
    - spirv
    - machine-learning

  # Triage perm for collaborators(test run)
  #
  # The perm is given based on needs and not based on
  # evaluation of past contributions. The rationale
  # is that people may need the permission to start
  # contributing in this way. It serves to diversify
  # the ways to contribute.
  #
  # There is a limited number of slots. To enable broad
  # participation, permission is given on a three month
  # cycle. PMC may review and recycle slots when necessary.
  collaborators:
    - hpanda-naut
    - denise-k
    - janetsc
    - naut-thomas
    - tvm-bot  # For automated feedback in PR review.

  # See https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection
  protected_branches:
    main:
      required_status_checks:
        contexts:
          # Require passing runs from Jenkins for all platforms
          - arm/pr-head
          - cortexm/pr-head
          - cpu/pr-head
          - docker/pr-head
          - gpu/pr-head
          - hexagon/pr-head
          - i386/pr-head
          - lint/pr-head
          - minimal/pr-head
          - riscv/pr-head
          - wasm/pr-head
          - cross-isa-minimal/pr-head

      required_pull_request_reviews:
        required_approving_review_count: 1
