#!/bin/bash -e
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

set -x

ARGS=( "$(basename $0)" )

if [ "${FVP_BIN_PATH}"  != "" ]; then
    ARGS=( ${FVP_BIN_PATH}/${ARGS[0]} )
fi

ARGS=( "${ARGS[@]}"
    --iris-server
    --print-port-number
    -C cpu0.semihosting-enable=1
    -C mps3_board.telnetterminal0.mode=raw
    -C mps3_board.telnetterminal1.mode=raw
    -C mps3_board.telnetterminal2.mode=raw
    -C mps3_board.telnetterminal0.start_telnet=0
    -C mps3_board.telnetterminal1.start_telnet=0
    -C mps3_board.telnetterminal2.start_telnet=0
    )

while [ "$#" -gt 0 ]; do
    ARGS=( "${ARGS[@]}" "$1" )
    shift
done

"${ARGS[@]}"
