/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include <stdio.h>
#include <tvm_runtime.h>
#include <tvmgen_model.h>

// Header files generated by convert.py
#include "inputs.h"
#include "outputs.h"

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

int main(int argc, char** argv) {
  printf("Running " TOSTRING(MODEL_NAME) " inference\n");
  struct tvmgen_model_outputs model_outputs = {
      MODEL_OUT_FIELD = output,
  };
  struct tvmgen_model_inputs model_inputs = {
      MODEL_IN_FIELD = input,
  };

  tvmgen_model_run(&model_inputs, &model_outputs);

  int index = 0;
  MODEL_OUT_TYPE* output_t = (MODEL_OUT_TYPE*)output;
  for (int i = 0; i < output_len; i++) {
    if (output_t[index] < output_t[i]) {
      index = i;
    }
  }

  // Report result
  if (index == MODEL_VALID_RES) {
    printf("Right result: " TOSTRING(MODEL_VALID_NAME) ".\n");
  } else {
    printf("Wrong result: %d != %d\n", index, MODEL_VALID_RES);
  }

  return 0;
}
