from tvm.relay.ir import NodeBase

class UnionFind(NodeBase): ...
class TypeUnifier(NodeBase): ...

def UnionFind_insert(self: UnionFind, var: ir.IncompleteType) -> None: ...
def UnionFind_unify(self: UnionFind, var1: ir.IncompleteType, var2: ir.IncompleteType) -> None: ...
def UnionFind_find(self: UnionFind, var: ir.IncompleteType) -> ir.Type: ...

def TypeUnifier_insert(self: TypeUnifier, var: ir.IncompleteType) -> None: ...
def TypeUnifier_unify(self, type1: ir.Type, type2: ir.Type) -> ir.Type: ...
def TypeUnifier_subst(self, type1: ir.Type) -> ir.Type: ...
