/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Generated by launch/generate.py; edit table.py instead.
#ifndef TVM_BACKEND_CUDA_LAUNCH_LAUNCH_ATTRIBUTES_H_
#define TVM_BACKEND_CUDA_LAUNCH_LAUNCH_ATTRIBUTES_H_
#include <cuda.h>
#include <cuda_runtime.h>

#include "launch_fields.h"
namespace tvm_cuda_launch {
inline constexpr size_t kMaxAttributes = 19;
inline unsigned EncodeDriverAttributes(const LaunchValues& config,
                                       std::array<CUlaunchAttribute, kMaxAttributes>* attrs,
                                       bool required_block_size) {
  unsigned count = 0;
  if (config.Has(Option::kCluster) && !required_block_size) {
#if CUDA_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_CLUSTER_DIMENSION;
    attr.value.clusterDim.x =
        static_cast<decltype(attr.value.clusterDim.x)>(config.Get(Field::kClusterX).integer);
    attr.value.clusterDim.y =
        static_cast<decltype(attr.value.clusterDim.y)>(config.Get(Field::kClusterY).integer);
    attr.value.clusterDim.z =
        static_cast<decltype(attr.value.clusterDim.z)>(config.Get(Field::kClusterZ).integer);
#else
    throw std::invalid_argument("CUDA launch field cluster requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kPreferredCluster) && !required_block_size) {
#if CUDA_VERSION >= 12080
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_PREFERRED_CLUSTER_DIMENSION;
    attr.value.preferredClusterDim.x = static_cast<decltype(attr.value.preferredClusterDim.x)>(
        config.Get(Field::kPreferredClusterX).integer);
    attr.value.preferredClusterDim.y = static_cast<decltype(attr.value.preferredClusterDim.y)>(
        config.Get(Field::kPreferredClusterY).integer);
    attr.value.preferredClusterDim.z = static_cast<decltype(attr.value.preferredClusterDim.z)>(
        config.Get(Field::kPreferredClusterZ).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field preferred_cluster requires toolkit 12.8 or newer");
#endif
  }
  if (config.Has(Option::kCooperative)) {
#if CUDA_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_COOPERATIVE;
    attr.value.cooperative =
        static_cast<decltype(attr.value.cooperative)>(config.Get(Field::kCooperative).integer);
#else
    throw std::invalid_argument("CUDA launch field cooperative requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kProgrammaticStreamSerialization)) {
#if CUDA_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_PROGRAMMATIC_STREAM_SERIALIZATION;
    attr.value.programmaticStreamSerializationAllowed =
        static_cast<decltype(attr.value.programmaticStreamSerializationAllowed)>(
            config.Get(Field::kProgrammaticStreamSerialization).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field programmatic_stream_serialization requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kClusterSchedulingPolicy)) {
#if CUDA_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_CLUSTER_SCHEDULING_POLICY_PREFERENCE;
    attr.value.clusterSchedulingPolicyPreference =
        static_cast<decltype(attr.value.clusterSchedulingPolicyPreference)>(
            config.Get(Field::kClusterSchedulingPolicy).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field cluster_scheduling_policy requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kPriority)) {
#if CUDA_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_PRIORITY;
    attr.value.priority =
        static_cast<decltype(attr.value.priority)>(config.Get(Field::kPriority).integer);
#else
    throw std::invalid_argument("CUDA launch field priority requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kMemSyncDomain)) {
#if CUDA_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_MEM_SYNC_DOMAIN;
    attr.value.memSyncDomain =
        static_cast<decltype(attr.value.memSyncDomain)>(config.Get(Field::kMemSyncDomain).integer);
#else
    throw std::invalid_argument("CUDA launch field mem_sync_domain requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kMemSyncDomainMap)) {
#if CUDA_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_MEM_SYNC_DOMAIN_MAP;
    attr.value.memSyncDomainMap.default_ =
        static_cast<decltype(attr.value.memSyncDomainMap.default_)>(
            config.Get(Field::kMemSyncDomainMapDefault).integer);
    attr.value.memSyncDomainMap.remote = static_cast<decltype(attr.value.memSyncDomainMap.remote)>(
        config.Get(Field::kMemSyncDomainMapRemote).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field mem_sync_domain_map requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kAccessPolicyWindow)) {
#if CUDA_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_ACCESS_POLICY_WINDOW;
    attr.value.accessPolicyWindow.base_ptr =
        static_cast<decltype(attr.value.accessPolicyWindow.base_ptr)>(
            config.Get(Field::kAccessPolicyWindowBasePtr).handle);
    attr.value.accessPolicyWindow.num_bytes =
        static_cast<decltype(attr.value.accessPolicyWindow.num_bytes)>(
            config.Get(Field::kAccessPolicyWindowNumBytes).integer);
    attr.value.accessPolicyWindow.hitRatio =
        static_cast<decltype(attr.value.accessPolicyWindow.hitRatio)>(
            config.Get(Field::kAccessPolicyWindowHitRatio).real);
    attr.value.accessPolicyWindow.hitProp =
        static_cast<decltype(attr.value.accessPolicyWindow.hitProp)>(
            config.Get(Field::kAccessPolicyWindowHitProp).integer);
    attr.value.accessPolicyWindow.missProp =
        static_cast<decltype(attr.value.accessPolicyWindow.missProp)>(
            config.Get(Field::kAccessPolicyWindowMissProp).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field access_policy_window requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kPreferredSharedMemoryCarveout)) {
#if CUDA_VERSION >= 12080
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_PREFERRED_SHARED_MEMORY_CARVEOUT;
    attr.value.sharedMemCarveout = static_cast<decltype(attr.value.sharedMemCarveout)>(
        config.Get(Field::kPreferredSharedMemoryCarveout).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field preferred_shared_memory_carveout requires toolkit 12.8 or newer");
#endif
  }
  if (config.Has(Option::kNvlinkUtilCentricScheduling)) {
#if CUDA_VERSION >= 13020
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_NVLINK_UTIL_CENTRIC_SCHEDULING;
    attr.value.nvlinkUtilCentricScheduling =
        static_cast<decltype(attr.value.nvlinkUtilCentricScheduling)>(
            config.Get(Field::kNvlinkUtilCentricScheduling).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field nvlink_util_centric_scheduling requires toolkit 13.2 or newer");
#endif
  }
  if (config.Has(Option::kPortableClusterSizeMode)) {
#if CUDA_VERSION >= 13020
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_PORTABLE_CLUSTER_SIZE_MODE;
    attr.value.portableClusterSizeMode = static_cast<decltype(attr.value.portableClusterSizeMode)>(
        config.Get(Field::kPortableClusterSizeMode).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field portable_cluster_size_mode requires toolkit 13.2 or newer");
#endif
  }
  if (config.Has(Option::kSharedMemoryMode)) {
#if CUDA_VERSION >= 13020
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_SHARED_MEMORY_MODE;
    attr.value.sharedMemoryMode = static_cast<decltype(attr.value.sharedMemoryMode)>(
        config.Get(Field::kSharedMemoryMode).integer);
#if CUDA_VERSION < 13040
    if (config.Int(Field::kSharedMemoryMode) > 2)
      throw std::invalid_argument("CUDA oversized shared memory requires CUDA 13.4 or newer");
#endif
#else
    throw std::invalid_argument(
        "CUDA launch field shared_memory_mode requires toolkit 13.2 or newer");
#endif
  }
  if (config.Has(Option::kProgrammaticEvent)) {
#if CUDA_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_PROGRAMMATIC_EVENT;
    attr.value.programmaticEvent.event = static_cast<decltype(attr.value.programmaticEvent.event)>(
        config.Get(Field::kProgrammaticEventEvent).handle);
    attr.value.programmaticEvent.flags = static_cast<decltype(attr.value.programmaticEvent.flags)>(
        config.Get(Field::kProgrammaticEventFlags).integer);
    attr.value.programmaticEvent.triggerAtBlockStart =
        static_cast<decltype(attr.value.programmaticEvent.triggerAtBlockStart)>(
            config.Get(Field::kProgrammaticEventTriggerAtBlockStart).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field programmatic_event requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kLaunchCompletionEvent)) {
#if CUDA_VERSION >= 12040
    auto& attr = (*attrs)[count++];
    attr.id = CU_LAUNCH_ATTRIBUTE_LAUNCH_COMPLETION_EVENT;
    attr.value.launchCompletionEvent.event =
        static_cast<decltype(attr.value.launchCompletionEvent.event)>(
            config.Get(Field::kLaunchCompletionEventEvent).handle);
    attr.value.launchCompletionEvent.flags =
        static_cast<decltype(attr.value.launchCompletionEvent.flags)>(
            config.Get(Field::kLaunchCompletionEventFlags).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field launch_completion_event requires toolkit 12.4 or newer");
#endif
  }
  return count;
}
inline unsigned EncodeRuntimeAttributes(const LaunchValues& config,
                                        std::array<cudaLaunchAttribute, kMaxAttributes>* attrs,
                                        bool required_block_size) {
  unsigned count = 0;
  if (config.Has(Option::kCluster) && !required_block_size) {
#if CUDART_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeClusterDimension;
    attr.val.clusterDim.x =
        static_cast<decltype(attr.val.clusterDim.x)>(config.Get(Field::kClusterX).integer);
    attr.val.clusterDim.y =
        static_cast<decltype(attr.val.clusterDim.y)>(config.Get(Field::kClusterY).integer);
    attr.val.clusterDim.z =
        static_cast<decltype(attr.val.clusterDim.z)>(config.Get(Field::kClusterZ).integer);
#else
    throw std::invalid_argument("CUDA launch field cluster requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kPreferredCluster) && !required_block_size) {
#if CUDART_VERSION >= 12080
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributePreferredClusterDimension;
    attr.val.preferredClusterDim.x = static_cast<decltype(attr.val.preferredClusterDim.x)>(
        config.Get(Field::kPreferredClusterX).integer);
    attr.val.preferredClusterDim.y = static_cast<decltype(attr.val.preferredClusterDim.y)>(
        config.Get(Field::kPreferredClusterY).integer);
    attr.val.preferredClusterDim.z = static_cast<decltype(attr.val.preferredClusterDim.z)>(
        config.Get(Field::kPreferredClusterZ).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field preferred_cluster requires toolkit 12.8 or newer");
#endif
  }
  if (config.Has(Option::kCooperative)) {
#if CUDART_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeCooperative;
    attr.val.cooperative =
        static_cast<decltype(attr.val.cooperative)>(config.Get(Field::kCooperative).integer);
#else
    throw std::invalid_argument("CUDA launch field cooperative requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kProgrammaticStreamSerialization)) {
#if CUDART_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeProgrammaticStreamSerialization;
    attr.val.programmaticStreamSerializationAllowed =
        static_cast<decltype(attr.val.programmaticStreamSerializationAllowed)>(
            config.Get(Field::kProgrammaticStreamSerialization).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field programmatic_stream_serialization requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kClusterSchedulingPolicy)) {
#if CUDART_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeClusterSchedulingPolicyPreference;
    attr.val.clusterSchedulingPolicyPreference =
        static_cast<decltype(attr.val.clusterSchedulingPolicyPreference)>(
            config.Get(Field::kClusterSchedulingPolicy).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field cluster_scheduling_policy requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kPriority)) {
#if CUDART_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributePriority;
    attr.val.priority =
        static_cast<decltype(attr.val.priority)>(config.Get(Field::kPriority).integer);
#else
    throw std::invalid_argument("CUDA launch field priority requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kMemSyncDomain)) {
#if CUDART_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeMemSyncDomain;
    attr.val.memSyncDomain =
        static_cast<decltype(attr.val.memSyncDomain)>(config.Get(Field::kMemSyncDomain).integer);
#else
    throw std::invalid_argument("CUDA launch field mem_sync_domain requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kMemSyncDomainMap)) {
#if CUDART_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeMemSyncDomainMap;
    attr.val.memSyncDomainMap.default_ = static_cast<decltype(attr.val.memSyncDomainMap.default_)>(
        config.Get(Field::kMemSyncDomainMapDefault).integer);
    attr.val.memSyncDomainMap.remote = static_cast<decltype(attr.val.memSyncDomainMap.remote)>(
        config.Get(Field::kMemSyncDomainMapRemote).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field mem_sync_domain_map requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kAccessPolicyWindow)) {
#if CUDART_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeAccessPolicyWindow;
    attr.val.accessPolicyWindow.base_ptr =
        static_cast<decltype(attr.val.accessPolicyWindow.base_ptr)>(
            config.Get(Field::kAccessPolicyWindowBasePtr).handle);
    attr.val.accessPolicyWindow.num_bytes =
        static_cast<decltype(attr.val.accessPolicyWindow.num_bytes)>(
            config.Get(Field::kAccessPolicyWindowNumBytes).integer);
    attr.val.accessPolicyWindow.hitRatio =
        static_cast<decltype(attr.val.accessPolicyWindow.hitRatio)>(
            config.Get(Field::kAccessPolicyWindowHitRatio).real);
    attr.val.accessPolicyWindow.hitProp =
        static_cast<decltype(attr.val.accessPolicyWindow.hitProp)>(
            config.Get(Field::kAccessPolicyWindowHitProp).integer);
    attr.val.accessPolicyWindow.missProp =
        static_cast<decltype(attr.val.accessPolicyWindow.missProp)>(
            config.Get(Field::kAccessPolicyWindowMissProp).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field access_policy_window requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kPreferredSharedMemoryCarveout)) {
#if CUDART_VERSION >= 12080
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributePreferredSharedMemoryCarveout;
    attr.val.sharedMemCarveout = static_cast<decltype(attr.val.sharedMemCarveout)>(
        config.Get(Field::kPreferredSharedMemoryCarveout).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field preferred_shared_memory_carveout requires toolkit 12.8 or newer");
#endif
  }
  if (config.Has(Option::kNvlinkUtilCentricScheduling)) {
#if CUDART_VERSION >= 13020
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeNvlinkUtilCentricScheduling;
    attr.val.nvlinkUtilCentricScheduling =
        static_cast<decltype(attr.val.nvlinkUtilCentricScheduling)>(
            config.Get(Field::kNvlinkUtilCentricScheduling).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field nvlink_util_centric_scheduling requires toolkit 13.2 or newer");
#endif
  }
  if (config.Has(Option::kPortableClusterSizeMode)) {
#if CUDART_VERSION >= 13020
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributePortableClusterSizeMode;
    attr.val.portableClusterSizeMode = static_cast<decltype(attr.val.portableClusterSizeMode)>(
        config.Get(Field::kPortableClusterSizeMode).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field portable_cluster_size_mode requires toolkit 13.2 or newer");
#endif
  }
  if (config.Has(Option::kSharedMemoryMode)) {
#if CUDART_VERSION >= 13020
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeSharedMemoryMode;
    attr.val.sharedMemoryMode = static_cast<decltype(attr.val.sharedMemoryMode)>(
        config.Get(Field::kSharedMemoryMode).integer);
#if CUDART_VERSION < 13040
    if (config.Int(Field::kSharedMemoryMode) > 2)
      throw std::invalid_argument("CUDA oversized shared memory requires CUDA 13.4 or newer");
#endif
#else
    throw std::invalid_argument(
        "CUDA launch field shared_memory_mode requires toolkit 13.2 or newer");
#endif
  }
  if (config.Has(Option::kProgrammaticEvent)) {
#if CUDART_VERSION >= 12000
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeProgrammaticEvent;
    attr.val.programmaticEvent.event = static_cast<decltype(attr.val.programmaticEvent.event)>(
        config.Get(Field::kProgrammaticEventEvent).handle);
    attr.val.programmaticEvent.flags = static_cast<decltype(attr.val.programmaticEvent.flags)>(
        config.Get(Field::kProgrammaticEventFlags).integer);
    attr.val.programmaticEvent.triggerAtBlockStart =
        static_cast<decltype(attr.val.programmaticEvent.triggerAtBlockStart)>(
            config.Get(Field::kProgrammaticEventTriggerAtBlockStart).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field programmatic_event requires toolkit 12.0 or newer");
#endif
  }
  if (config.Has(Option::kLaunchCompletionEvent)) {
#if CUDART_VERSION >= 12040
    auto& attr = (*attrs)[count++];
    attr.id = cudaLaunchAttributeLaunchCompletionEvent;
    attr.val.launchCompletionEvent.event =
        static_cast<decltype(attr.val.launchCompletionEvent.event)>(
            config.Get(Field::kLaunchCompletionEventEvent).handle);
    attr.val.launchCompletionEvent.flags =
        static_cast<decltype(attr.val.launchCompletionEvent.flags)>(
            config.Get(Field::kLaunchCompletionEventFlags).integer);
#else
    throw std::invalid_argument(
        "CUDA launch field launch_completion_event requires toolkit 12.4 or newer");
#endif
  }
  return count;
}
}  // namespace tvm_cuda_launch
#endif
