#!/bin/bash -e
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Zephyr insists on running qemu with a -pidfile option, but that option doesn't appear to
# work given the way we've configured docker (the underlying filesystem doesn't suppor the
# file locking it needs to). This script strips any -pidfile option, then invokes qemu.

ARGS=( "$(basename $0)" )
while [ "$#" -gt 0 ]; do
    if [ "$1" == "-pidfile" ]; then
        shift
    else
        ARGS=( "${ARGS[@]}" "$1" )
    fi
    shift
done

# For debugging
if [ "${TVM_QEMU_DEBUG}" != "" ]; then
    ARGS=( "${ARGS[@]}" -s -S )
fi

"${ARGS[@]}"
