# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""FFI APIs"""
# tvm-ffi-stubgen(begin): import-section
# fmt: off
# isort: off
from __future__ import annotations
from tvm_ffi import init_ffi_api as _FFI_INIT_FUNC
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence
    from ir import IntImm, PrimExpr, Range, Type
    from script.ir_builder.tir import AllocateConstFrame, AllocateFrame, AssertFrame, AttrFrame, BlockFrame, BlockInitFrame, DeclBufferFrame, ElseFrame, ForFrame, IfFrame, LaunchThreadFrame, LetFrame, PrimFuncFrame, RealizeFrame, ThenFrame, WhileFrame
    from tir import Buffer, BufferRegion, Var
    from tvm_ffi import Object, Tensor, dtype
    from typing import Any
# isort: on
# fmt: on
# tvm-ffi-stubgen(end)


# tvm-ffi-stubgen(begin): global/script.ir_builder.tir
# fmt: off
_FFI_INIT_FUNC("script.ir_builder.tir", __name__)
if TYPE_CHECKING:
    def AllocBuffer(_0: Sequence[PrimExpr], _1: dtype, _2: Var | None, _3: Sequence[PrimExpr], _4: PrimExpr, _5: str, _6: int, _7: int, _8: str, _9: Sequence[IntImm] | None, /) -> Buffer: ...
    def Allocate(_0: Sequence[PrimExpr], _1: dtype, _2: str, _3: PrimExpr | None, _4: Mapping[str, Any] | None, /) -> AllocateFrame: ...
    def AllocateConst(_0: Tensor, _1: dtype, _2: Sequence[PrimExpr], _3: Mapping[str, Any] | None, /) -> AllocateConstFrame: ...
    def Arg(_0: str, _1: Object, /) -> Object: ...
    def Assert(_0: PrimExpr, _1: str, /) -> AssertFrame: ...
    def Attr(_0: Any, _1: str, _2: PrimExpr, /) -> AttrFrame: ...
    def AxisOpaque(_0: Range, _1: PrimExpr, _2: dtype, /) -> Var: ...
    def AxisReduce(_0: Range, _1: PrimExpr, _2: dtype, /) -> Var: ...
    def AxisRemap(_0: str, _1: Sequence[PrimExpr], _2: dtype, /) -> Sequence[Var]: ...
    def AxisScan(_0: Range, _1: PrimExpr, _2: dtype, /) -> Var: ...
    def AxisSpatial(_0: Range, _1: PrimExpr, _2: dtype, /) -> Var: ...
    def BFloat16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def BFloat16x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def BFloat16x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def BFloat16x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def BFloat16x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def BFloat16x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Block(_0: str, _1: bool, /) -> BlockFrame: ...
    def BlockAttrs(_0: Mapping[str, Any], /) -> None: ...
    def Boolean(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Buffer(_0: Sequence[PrimExpr], _1: dtype, _2: str, _3: Var | None, _4: Sequence[PrimExpr] | None, _5: PrimExpr | None, _6: str, _7: int, _8: int, _9: str, _10: Sequence[IntImm] | None, /) -> Buffer: ...
    def BufferStore(_0: Buffer, _1: PrimExpr, _2: Sequence[PrimExpr], _3: PrimExpr | None, /) -> None: ...
    def DeclBuffer(_0: Sequence[PrimExpr], _1: dtype, _2: str, _3: Var | None, _4: Sequence[PrimExpr] | None, _5: PrimExpr | None, _6: str, _7: int, _8: int, _9: str, _10: Sequence[IntImm] | None, /) -> DeclBufferFrame: ...
    def Else() -> ElseFrame: ...
    def EnvThread(_0: str, _1: dtype, /) -> Var: ...
    def Evaluate(_0: PrimExpr, /) -> None: ...
    def Float16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float16x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float16x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float16x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float16x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float16x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float32x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float32x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float32x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float32x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float32x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float4E2M1FN(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float4E2M1FNx16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float4E2M1FNx32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float4E2M1FNx4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float4E2M1FNx64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float4E2M1FNx8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float64x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float64x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float64x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float64x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float64x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E2M3FN(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E2M3FNx16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E2M3FNx32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E2M3FNx4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E2M3FNx64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E2M3FNx8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E3M2FN(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E3M2FNx16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E3M2FNx32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E3M2FNx4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E3M2FNx64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float6E3M2FNx8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E3M4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E3M4x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E3M4x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E3M4x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E3M4x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E3M4x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3B11FNUZ(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3B11FNUZx16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3B11FNUZx32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3B11FNUZx4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3B11FNUZx64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3B11FNUZx8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FN(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNUZ(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNUZx16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNUZx32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNUZx4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNUZx64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNUZx8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNx16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNx32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNx4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNx64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3FNx8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E4M3x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2FNUZ(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2FNUZx16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2FNUZx32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2FNUZx4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2FNUZx64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2FNUZx8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E5M2x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E8M0FNU(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E8M0FNUx16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E8M0FNUx32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E8M0FNUx4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E8M0FNUx64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8E8M0FNUx8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Float8x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def FuncAttrs(_0: Mapping[str, Any], /) -> None: ...
    def FuncName(_0: str, /) -> None: ...
    def FuncRet(_0: Type, /) -> Type: ...
    def Grid(_0: Sequence[PrimExpr], /) -> ForFrame: ...
    def Handle(_0: dtype, _1: str, _2: bool, _3: bool, /) -> Var: ...
    def If(_0: PrimExpr, /) -> IfFrame: ...
    def Init() -> BlockInitFrame: ...
    def Int16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int16x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int16x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int16x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int16x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int16x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int32x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int32x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int32x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int32x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int32x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int64x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int64x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int64x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int64x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int64x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int8x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int8x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int8x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int8x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Int8x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def LaunchThread(_0: Var | str, _1: PrimExpr, /) -> LaunchThreadFrame: ...
    def LegacyLetStmt(_0: Var, _1: PrimExpr, /) -> LetFrame: ...
    def LetStmt(_0: PrimExpr, _1: Type | None, _2: Var | None, /) -> LetFrame: ...
    def MatchBuffer(_0: Object, _1: Sequence[PrimExpr], _2: dtype, _3: Var | None, _4: Sequence[PrimExpr], _5: PrimExpr, _6: str, _7: int, _8: int, _9: str, _10: Sequence[IntImm] | None, /) -> Buffer: ...
    def Parallel(_0: PrimExpr, _1: PrimExpr, _2: Mapping[str, Any] | None, _3: PrimExpr | None, /) -> ForFrame: ...
    def PrimFunc(_0: bool, /) -> PrimFuncFrame: ...
    def Ptr(_0: dtype, _1: str, _2: bool, /) -> PrimExpr: ...
    def Reads(_0: Sequence[Object], /) -> None: ...
    def Realize(_0: BufferRegion, _1: str, _2: PrimExpr, /) -> RealizeFrame: ...
    def Serial(_0: PrimExpr, _1: PrimExpr, _2: Mapping[str, Any] | None, _3: PrimExpr | None, /) -> ForFrame: ...
    def TensormapHandle() -> Var: ...
    def Then() -> ThenFrame: ...
    def ThreadBinding(_0: PrimExpr, _1: PrimExpr, _2: str, _3: Mapping[str, Any] | None, /) -> ForFrame: ...
    def UInt16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt16x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt16x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt16x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt16x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt16x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt32x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt32x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt32x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt32x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt32x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt64x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt64x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt64x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt64x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt64x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt8x16(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt8x32(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt8x4(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt8x64(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def UInt8x8(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Unroll(_0: PrimExpr, _1: PrimExpr, _2: Mapping[str, Any] | None, _3: PrimExpr | None, /) -> ForFrame: ...
    def Vectorized(_0: PrimExpr, _1: PrimExpr, _2: Mapping[str, Any] | None, _3: PrimExpr | None, /) -> ForFrame: ...
    def Void(_0: PrimExpr | None, _1: bool, /) -> PrimExpr: ...
    def Where(_0: PrimExpr, /) -> None: ...
    def While(_0: PrimExpr, /) -> WhileFrame: ...
    def Writes(_0: Sequence[Object], /) -> None: ...
    def max(_0: PrimExpr, _1: PrimExpr, /) -> PrimExpr: ...
    def min(_0: PrimExpr, _1: PrimExpr, /) -> PrimExpr: ...
# fmt: on
# tvm-ffi-stubgen(end)
