# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""FFI APIs for tvm.arith"""
# tvm-ffi-stubgen(begin): import-section
# fmt: off
# isort: off
from __future__ import annotations
from tvm_ffi import init_ffi_api as _FFI_INIT_FUNC
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from arith import ConstIntBound, IntConstraints, IntConstraintsTransform, IntGroupBounds, IntervalSet, IterMark, IterSplitExpr, IterSumExpr, ModularSet
    from collections.abc import Mapping, Sequence
    from ir import IntImm, IntSet, PrimExpr, Range
    from tir import Buffer, PrimFunc, Stmt, Var
    from tvm_ffi import Object
    from typing import Any
# isort: on
# fmt: on
# tvm-ffi-stubgen(end)



# tvm-ffi-stubgen(begin): global/arith
# fmt: off
_FFI_INIT_FUNC("arith", __name__)
if TYPE_CHECKING:
    def ConstIntBound(_0: int, _1: int, /) -> ConstIntBound: ...
    def CreateAnalyzer(*args: Any) -> Any: ...
    def DeduceBound(_0: PrimExpr, _1: PrimExpr, _2: Mapping[Var, IntSet], _3: Mapping[Var, IntSet], /) -> IntSet: ...
    def DetectClipBound(_0: PrimExpr, _1: Sequence[Var], /) -> Sequence[PrimExpr]: ...
    def DetectCommonSubExpr(_0: PrimExpr, _1: int, /) -> Mapping[PrimExpr, IntImm]: ...
    def DetectIterMap(_0: Sequence[PrimExpr], _1: Mapping[Var, Range], _2: PrimExpr, _3: int, _4: bool, /) -> Object: ...
    def DetectLinearEquation(_0: PrimExpr, _1: Sequence[Var], /) -> Sequence[PrimExpr]: ...
    def DomainTouched(_0: Stmt, _1: Buffer, _2: bool, _3: bool, /) -> Sequence[Range]: ...
    def DomainTouchedAccessMap(_0: PrimFunc, /) -> Mapping[Buffer, Sequence[Object]]: ...
    def EstimateRegionLowerBound(_0: Sequence[Range], _1: Mapping[Var, Range], _2: PrimExpr, /) -> Sequence[IntSet] | None: ...
    def EstimateRegionStrictBound(_0: Sequence[Range], _1: Mapping[Var, Range], _2: PrimExpr, /) -> Sequence[IntSet] | None: ...
    def EstimateRegionUpperBound(_0: Sequence[Range], _1: Mapping[Var, Range], _2: PrimExpr, /) -> Sequence[IntSet] | None: ...
    def IntConstraints(_0: Sequence[Var], _1: Mapping[Var, Range], _2: Sequence[PrimExpr], /) -> IntConstraints: ...
    def IntConstraintsTransform(_0: IntConstraints, _1: IntConstraints, _2: Mapping[Var, PrimExpr], _3: Mapping[Var, PrimExpr], /) -> IntConstraintsTransform: ...
    def IntGroupBounds(_0: PrimExpr, _1: Sequence[PrimExpr], _2: Sequence[PrimExpr], _3: Sequence[PrimExpr], /) -> IntGroupBounds: ...
    def IntGroupBounds_FindBestRange(*args: Any) -> Any: ...
    def IntGroupBounds_from_range(_0: Range, /) -> IntGroupBounds: ...
    def IntSetIsEverything(_0: IntSet, /) -> bool: ...
    def IntSetIsNothing(_0: IntSet, /) -> bool: ...
    def IntervalSet(_0: PrimExpr, _1: PrimExpr, /) -> IntervalSet: ...
    def IntervalSetGetMax(_0: IntSet, /) -> PrimExpr: ...
    def IntervalSetGetMin(_0: IntSet, /) -> PrimExpr: ...
    def InverseAffineIterMap(_0: Sequence[IterSumExpr], _1: Sequence[PrimExpr], /) -> Mapping[Var, PrimExpr]: ...
    def IterMapSimplify(_0: Sequence[PrimExpr], _1: Mapping[Var, Range], _2: PrimExpr, _3: int, _4: bool, /) -> Sequence[PrimExpr]: ...
    def IterMark(_0: PrimExpr, _1: PrimExpr, /) -> IterMark: ...
    def IterSplitExpr(_0: IterMark, _1: PrimExpr, _2: PrimExpr, _3: PrimExpr, /) -> IterSplitExpr: ...
    def IterSumExpr(_0: Sequence[IterSplitExpr], _1: PrimExpr, /) -> IterSumExpr: ...
    def ModularSet(_0: int, _1: int, /) -> ModularSet: ...
    def NarrowPredicateExpression(_0: PrimExpr, _1: Mapping[Var, Range], /) -> PrimExpr: ...
    def NegInf() -> PrimExpr: ...
    def NormalizeIterMapToExpr(_0: PrimExpr, /) -> PrimExpr: ...
    def NormalizeToIterSum(_0: PrimExpr, _1: Mapping[Var, Range], /) -> IterSumExpr: ...
    def PosInf() -> PrimExpr: ...
    def PresburgerSet(_0: PrimExpr, /) -> IntSet: ...
    def SolveInequalitiesAsCondition(*args: Any) -> Any: ...
    def SolveInequalitiesDeskewRange(*args: Any) -> Any: ...
    def SolveInequalitiesToRange(*args: Any) -> Any: ...
    def SolveLinearEquations(*args: Any) -> Any: ...
    def SubspaceDivide(_0: Sequence[PrimExpr], _1: Mapping[Var, Range], _2: Sequence[Var], _3: PrimExpr, _4: int, _5: bool, /) -> Sequence[Sequence[IterMark]]: ...
    def UnionLowerBound(_0: Sequence[IntSet], /) -> IntSet: ...
    def intset_interval(_0: PrimExpr, _1: PrimExpr, /) -> IntSet: ...
    def intset_single_point(_0: PrimExpr, /) -> IntSet: ...
    def intset_vector(_0: PrimExpr, /) -> IntSet: ...
# fmt: on
# tvm-ffi-stubgen(end)
