# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""FFI APIs for tvm.script.printer"""
# tvm-ffi-stubgen(begin): import-section
# fmt: off
# isort: off
from __future__ import annotations
from tvm_ffi import init_ffi_api as _FFI_INIT_FUNC
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from collections.abc import Sequence
    from script import PrinterConfig
    from script.printer import AssertDoc, AssignDoc, AttrAccessDoc, CallDoc, ClassDoc, CommentDoc, DictDoc, Doc, DocStringDoc, ExprDoc, ExprStmtDoc, ForDoc, FunctionDoc, IdDoc, IfDoc, IndexDoc, LambdaDoc, ListDoc, LiteralDoc, OperationDoc, ReturnDoc, ScopeDoc, SliceDoc, StmtBlockDoc, StmtDoc, TupleDoc, WhileDoc
    from tvm_ffi import Object
    from tvm_ffi.reflection import AccessPath
# isort: on
# fmt: on
# tvm-ffi-stubgen(end)


# tvm-ffi-stubgen(begin): global/script.printer
# fmt: off
_FFI_INIT_FUNC("script.printer", __name__)
if TYPE_CHECKING:
    def AssertDoc(_0: ExprDoc, _1: ExprDoc | None, /) -> AssertDoc: ...
    def AssignDoc(_0: ExprDoc, _1: ExprDoc | None, _2: ExprDoc | None, /) -> AssignDoc: ...
    def AttrAccessDoc(_0: ExprDoc, _1: str, /) -> AttrAccessDoc: ...
    def CallDoc(_0: ExprDoc, _1: Sequence[ExprDoc], _2: Sequence[str], _3: Sequence[ExprDoc], /) -> CallDoc: ...
    def ClassDoc(_0: IdDoc, _1: Sequence[ExprDoc], _2: Sequence[StmtDoc], /) -> ClassDoc: ...
    def CommentDoc(_0: str, /) -> CommentDoc: ...
    def DictDoc(_0: Sequence[ExprDoc], _1: Sequence[ExprDoc], /) -> DictDoc: ...
    def DocSetSourcePaths(_0: Doc, _1: Sequence[AccessPath], /) -> None: ...
    def DocStringDoc(_0: str, /) -> DocStringDoc: ...
    def DocToPythonScript(_0: Doc, _1: PrinterConfig, /) -> str: ...
    def ExprDocAttr(_0: ExprDoc, _1: str, /) -> ExprDoc: ...
    def ExprDocCall(_0: ExprDoc, _1: Sequence[ExprDoc], _2: Sequence[str], _3: Sequence[ExprDoc], /) -> ExprDoc: ...
    def ExprDocIndex(_0: ExprDoc, _1: Sequence[Doc], /) -> ExprDoc: ...
    def ExprStmtDoc(_0: ExprDoc, /) -> ExprStmtDoc: ...
    def ForDoc(_0: ExprDoc, _1: ExprDoc, _2: Sequence[StmtDoc], /) -> ForDoc: ...
    def FunctionDoc(_0: IdDoc, _1: Sequence[AssignDoc], _2: Sequence[ExprDoc], _3: ExprDoc | None, _4: Sequence[StmtDoc], /) -> FunctionDoc: ...
    def IdDoc(_0: str, /) -> IdDoc: ...
    def IfDoc(_0: ExprDoc, _1: Sequence[StmtDoc], _2: Sequence[StmtDoc], /) -> IfDoc: ...
    def IndexDoc(_0: ExprDoc, _1: Sequence[Doc], /) -> IndexDoc: ...
    def LambdaDoc(_0: Sequence[IdDoc], _1: ExprDoc, /) -> LambdaDoc: ...
    def ListDoc(_0: Sequence[ExprDoc], /) -> ListDoc: ...
    def LiteralDocBoolean(_0: bool, _1: AccessPath | None, /) -> LiteralDoc: ...
    def LiteralDocFloat(_0: float, _1: AccessPath | None, /) -> LiteralDoc: ...
    def LiteralDocInt(_0: int, _1: AccessPath | None, /) -> LiteralDoc: ...
    def LiteralDocNone(_0: AccessPath | None, /) -> LiteralDoc: ...
    def LiteralDocStr(_0: str, _1: AccessPath | None, /) -> LiteralDoc: ...
    def OperationDoc(_0: int, _1: Sequence[ExprDoc], /) -> OperationDoc: ...
    def ReprPrintRelax(_0: Object, _1: PrinterConfig, /) -> str: ...
    def ReturnDoc(_0: ExprDoc, /) -> ReturnDoc: ...
    def ScopeDoc(_0: ExprDoc | None, _1: ExprDoc, _2: Sequence[StmtDoc], /) -> ScopeDoc: ...
    def SliceDoc(_0: ExprDoc | None, _1: ExprDoc | None, _2: ExprDoc | None, /) -> SliceDoc: ...
    def StmtBlockDoc(_0: Sequence[StmtDoc], /) -> StmtBlockDoc: ...
    def StmtDocSetComment(_0: StmtDoc, _1: str | None, /) -> None: ...
    def TupleDoc(_0: Sequence[ExprDoc], /) -> TupleDoc: ...
    def WhileDoc(_0: ExprDoc, _1: Sequence[StmtDoc], /) -> WhileDoc: ...
# fmt: on
# tvm-ffi-stubgen(end)
