blank_issues_enabled: false  # default: true
contact_links:
- name: 💬 Discourse
  url: https://discuss.tvm.apache.org/
  about: Thanks for participating in the TVM community! We use https://discuss.tvm.ai for any general usage questions and discussions. The issue tracker is used for actionable items such as feature proposals discussion, roadmaps, and bug tracking.  You are always welcomed to post on the forum first 😺
