/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*!
 * \file tvm/ir/op.h
 * \brief Canonical primitive operators and their registration.
 */
#ifndef TVM_IR_OP_H_
#define TVM_IR_OP_H_

#include <tvm/ffi/container/list.h>
#include <tvm/ffi/error.h>
#include <tvm/ffi/function.h>
#include <tvm/ffi/reflection/registry.h>
#include <tvm/ir/attrs.h>
#include <tvm/ir/env_func.h>
#include <tvm/ir/expr.h>
#include <tvm/ir/type.h>

#include <type_traits>
#include <utility>

namespace tvm {

template <typename>
class OpAttrMap;

/*! \brief An operator argument's name, IR representation schema, and documentation. */
class ArgumentInfoNode : public ffi::Object {
 public:
  /*! \brief Argument name. */
  ffi::String name;
  /*! \brief JSON schema of the IR representation, generated by native FFI reflection. */
  ffi::String ir_type_schema;
  /*! \brief Argument documentation. */
  ffi::String doc;

  static void RegisterReflection() {
    namespace refl = ffi::reflection;
    refl::ObjectDef<ArgumentInfoNode>()
        .def_ro("name", &ArgumentInfoNode::name)
        .def_ro("ir_type_schema", &ArgumentInfoNode::ir_type_schema)
        .def_ro("doc", &ArgumentInfoNode::doc);
  }

  static constexpr TVMFFISEqHashKind _type_s_eq_hash_kind = kTVMFFISEqHashKindTreeNode;
  TVM_FFI_DECLARE_OBJECT_INFO_FINAL("ir.ArgumentInfo", ArgumentInfoNode, ffi::Object);
};

/*! \brief Managed reference to an argument descriptor. */
class ArgumentInfo : public ffi::ObjectRef {
 public:
  TVM_FFI_DEFINE_OBJECT_REF_METHODS_NULLABLE(ArgumentInfo, ffi::ObjectRef, ArgumentInfoNode);
};

/*! \brief Metadata for a canonical primitive operator invoked through Call. */
class OpNode : public ExprNode {
 public:
  /*! \brief Canonical operator name. */
  ffi::String name;
  /*! \brief Operator documentation. */
  ffi::String doc;
  /*! \brief Descriptors for the ordered required value-argument prefix. */
  ffi::Array<ArgumentInfo> args_info;
  /*! \brief Accept at least args_info.size() value arguments when true, exactly that count
   * otherwise. */
  bool allow_extra_args{false};
  /*! \brief Descriptors for Call.ty_args; inference owns optional/variable type-argument checks. */
  ffi::Array<ArgumentInfo> ty_args_info;
  /*! \brief Attribute object type key, or empty when unrestricted. */
  ffi::String attrs_type_key;
  /*! \brief Runtime index corresponding to attrs_type_key; not serialized. */
  uint32_t attrs_type_index{0};

  TVM_DLL static void RegisterReflection();

  static constexpr TVMFFISEqHashKind _type_s_eq_hash_kind = kTVMFFISEqHashKindUniqueInstance;
  TVM_FFI_DECLARE_OBJECT_INFO_FINAL("ir.Op", OpNode, ExprNode);

 private:
  friend class OpRegistry;
  friend class OpDef;
  template <typename>
  friend class OpAttrMap;
  // Dense process-local index into attribute columns; never serialized.
  uint32_t index_{0};
};

/*!
 * \brief Reference-counted handle to a canonical named operator.
 *
 * OpDef temporarily builds metadata on the same Op returned by Get. Independent
 * registrations may attach different attributes; replacing an existing attribute
 * requires explicit override. Cached attribute maps observe subsequent changes.
 * args_info describes required value operands; allow_extra_args permits a suffix.
 * ty_args_info describes type arguments without changing their inference rules.
 *
 * \code
 * TVM_FFI_STATIC_INIT_BLOCK() {
 *   OpDef("example.identity", "Return the input expression.")
 *       .arg<Expr>("value", "The input expression.")
 *       .set_attr<bool>("FPurity", true);
 * }
 * // Copies the handle; the canonical node is shared.
 * Op op = Op::Get("example.identity");
 * bool pure = Op::GetAttrMap<bool>("FPurity")[op];
 * \endcode
 */
class Op : public Expr {
 public:
  /*! \brief Construct a handle from a defined node. \param n The operator node. */
  explicit Op(ffi::ObjectPtr<OpNode> n) : Expr(std::move(n)) {
    TVM_FFI_CHECK(defined(), ValueError) << "Op expects a defined OpNode";
  }

  /*!
   * \brief Get a typed live view of a registered attribute column.
   * \tparam ValueType The attribute value type.
   * \param attr_name The column name.
   * \return A shared view that observes registration, replacement, reset, and growth.
   * \throws InternalError if the column has never been registered.
   */
  template <typename ValueType>
  static OpAttrMap<ValueType> GetAttrMap(const ffi::String& attr_name);
  /*!
   * \brief Check whether an attribute column exists, even if some Ops lack a value.
   * \param attr_name The column name.
   * \return Whether the column has been registered.
   */
  TVM_DLL static bool HasAttrMap(const ffi::String& attr_name);
  /*!
   * \brief Look up a registered operator by name.
   * \param op_name The canonical name.
   * \return A copy of the reference-counted handle to the canonical node.
   * \throws AttributeError if the operator is not registered.
   */
  TVM_DLL static Op Get(const ffi::String& op_name);
  /*! \brief List registered operator names. \return Names in unspecified order. */
  TVM_DLL static ffi::Array<ffi::String> ListNames();

  TVM_FFI_DEFINE_OBJECT_REF_METHODS_NOTNULLABLE(Op, Expr, OpNode);

 private:
  TVM_DLL static ffi::List<ffi::Any> GetAttrColumn(const ffi::String& attr_name);
};

/*! \brief Temporary builder for a canonical Op; see Op for the registration example. */
class OpDef {
 public:
  /*!
   * \brief Get or create the named Op without changing its documentation.
   * \param name The canonical operator name.
   */
  TVM_DLL explicit OpDef(const ffi::String& name);
  /*!
   * \brief Get or create the named Op and set its documentation.
   * \param name The canonical operator name.
   * \param doc Operator documentation, replacing any existing documentation.
   */
  TVM_DLL OpDef(const ffi::String& name, const ffi::String& doc);
  /*! \brief Get the canonical operator. \return A copied handle, safe after this builder dies. */
  Op op() const { return op_; }
  /*!
   * \brief Append a required value-argument descriptor using the native FFI schema for T.
   * \tparam T The operand representation type, not its runtime tensor value type.
   * \param name Argument name.
   * \param doc Argument documentation.
   * \return This builder. Without allow_extra_args(), the prefix is the complete argument list.
   */
  template <typename T>
  OpDef& arg(const ffi::String& name, const ffi::String& doc) {
    return arg(name, ffi::details::TypeSchema<T>::v(), doc);
  }
  /*!
   * \brief Append an argument descriptor with an already generated FFI schema.
   * \param name Argument name.
   * \param ir_type_schema JSON schema of the IR representation.
   * \param doc Argument documentation.
   * \return This builder; does not validate operands.
   */
  TVM_DLL OpDef& arg(const ffi::String& name, const ffi::String& ir_type_schema,
                     const ffi::String& doc);
  /*!
   * \brief Set the attribute object type key and runtime index together.
   * \tparam AttrsType The attribute object node type.
   * \return This builder.
   */
  template <typename AttrsType>
  OpDef& call_attrs_type() {
    uint32_t index = AttrsType::RuntimeTypeIndex();
    get()->attrs_type_key = AttrsType::_type_key;
    get()->attrs_type_index = index;
    return *this;
  }
  /*!
   * \brief Resolve and set the attribute object type key and runtime index together.
   * \param key A registered attribute object type key.
   * \return This builder. An unknown key raises an error before modifying metadata.
   */
  TVM_DLL OpDef& set_attrs_type_key(const ffi::String& key);
  /*!
   * \brief Allow value arguments after the required prefix described by args_info.
   * \return This builder. An empty prefix accepts any number of value arguments.
   */
  OpDef& allow_extra_args() {
    get()->allow_extra_args = true;
    return *this;
  }
  /*!
   * \brief Append a descriptor for a type argument in Call.ty_args.
   * \tparam T The type-argument representation type.
   * \param name Type-argument name.
   * \param doc Type-argument documentation.
   * \return This builder. Inference retains responsibility for type-argument counts.
   */
  template <typename T>
  OpDef& ty_arg(const ffi::String& name, const ffi::String& doc) {
    return ty_arg(name, ffi::details::TypeSchema<T>::v(), doc);
  }
  /*!
   * \brief Append a type-argument descriptor with an already generated FFI schema.
   * \param name Type-argument name.
   * \param ir_type_schema JSON schema of the IR representation.
   * \param doc Type-argument documentation.
   * \return This builder; does not validate type-argument counts.
   */
  TVM_DLL OpDef& ty_arg(const ffi::String& name, const ffi::String& ir_type_schema,
                        const ffi::String& doc);
  /*!
   * \brief Register an extensible attribute, rejecting duplicates unless overridden.
   * \tparam ValueType The attribute value type.
   * \param attr_name Attribute column name.
   * \param value Non-null attribute value.
   * \param override Whether to replace an existing value; no prior value is retained.
   * \return This builder. Existing cached maps observe the new value.
   */
  template <typename ValueType>
  OpDef& set_attr(const ffi::String& attr_name, const ValueType& value, bool override = false) {
    UpdateAttr(attr_name, ffi::Any(value), override);
    return *this;
  }
  /*!
   * \brief Remove the current attribute value, with no priority fallback.
   * \param attr_name Attribute column name; missing columns and values are ignored.
   * \return This builder. Existing cached maps observe the removal.
   */
  TVM_DLL OpDef& reset_attr(const ffi::String& attr_name);

 private:
  OpNode* get() { return const_cast<OpNode*>(op_.operator->()); }
  TVM_DLL void UpdateAttr(const ffi::String& attr_name, ffi::Any value, bool override);
  Op op_;
};

/*!
 * \brief Typed live view of an Op attribute column.
 *
 * Copies share the retained mutable column and observe later registrations,
 * replacements, resets, and growth. Values are returned by value, never as
 * references into a backing array. Registration is not synchronized with readers.
 * \tparam ValueType The attribute value type.
 */
template <typename ValueType>
class OpAttrMap {
 public:
  /*!
   * \brief Check whether an operator has a value in this column.
   * \param op The operator.
   * \return 1 if present, 0 otherwise.
   */
  int count(const Op& op) const {
    return op->index_ < column_.size() && column_[op->index_] != nullptr;
  }
  /*!
   * \brief Look up an operator's attribute, raising InternalError if absent.
   * \param op The operator.
   * \return The value converted to ValueType.
   */
  ValueType operator[](const Op& op) const {
    TVM_FFI_ICHECK(count(op)) << "Attribute " << attr_name_ << " has not been registered for "
                            << op->name;
    if constexpr (std::is_same_v<ValueType, ffi::Any>) {
      return column_[op->index_];
    } else {
      return column_[op->index_].template cast<ValueType>();
    }
  }
  /*!
   * \brief Look up an operator's attribute with a fallback.
   * \param op The operator.
   * \param def_value Fallback when the attribute is absent.
   * \return The registered value or def_value.
   */
  ValueType get(const Op& op, ValueType def_value) const {
    return count(op) ? (*this)[op] : def_value;
  }
  /*!
   * \brief Look up an expression's attribute with a fallback.
   * \param expr A defined expression.
   * \param def_value Fallback when expr is not an Op or its attribute is absent.
   * \return The registered value or def_value.
   */
  ValueType get(const Expr& expr, ValueType def_value) const {
    TVM_FFI_ICHECK(expr.defined());
    if (const auto* op = expr.as<OpNode>()) {
      return get(ffi::GetRef<Op>(op), def_value);
    }
    return def_value;
  }

 private:
  friend class Op;
  OpAttrMap(ffi::List<ffi::Any> column, ffi::String attr_name)
      : column_(std::move(column)), attr_name_(std::move(attr_name)) {}
  ffi::List<ffi::Any> column_;
  ffi::String attr_name_;
};

template <typename ValueType>
OpAttrMap<ValueType> Op::GetAttrMap(const ffi::String& attr_name) {
  return OpAttrMap<ValueType>(GetAttrColumn(attr_name), attr_name);
}

}  // namespace tvm
#endif  // TVM_IR_OP_H_
