{% set version = "0.5.dev" %}

package:
  name: nnvm
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - cython
    - numpy
    - setuptools
    - decorator
    - tvm-libs =={{ version }}
  run:
    - tvm =={{ version }}
    - topi =={{ version }}
    - tvm-libs =={{ version }}
    - python
    - {{ pin_compatible('numpy') }}
    - decorator

test:
  imports:
    - nnvm

about:
  home: https://github.com/dmlc/nnvm
  license: Apache2
  summary: Bring deep learning to bare metal
