# For CPU
FROM ubuntu:14.04

RUN apt-get update

COPY install/ubuntu_*.sh /install/
RUN bash /install/ubuntu_install_core.sh
RUN apt-get update && apt-get install -y python-pip
RUN bash /install/ubuntu_install_python.sh
RUN bash /install/ubuntu_install_iverilog.sh
