{% set version = "0.5.dev" %}

package:
  name: tvm
  version: {{ version }}

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - cython
    - numpy
    - setuptools
    - decorator
    - tvm-libs =={{ version }}
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - decorator
    - tvm-libs =={{ version }}

test:
  imports:
    - tvm

about:
  home: https://github.com/dmlc/tvm
  license: Apache2
  summary: a low level domain specific language for compiling tensor computation pipelines
