{% set version = "0.4.dev" %}

package:
  name: tvm-libs
  version: {{ version }}

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    # The compiler on mac comes bundled with a broken llvm that overwrites
    # the llvmdev package
    - {{ compiler('cxx') }}  # [not osx]
    - llvmdev ==6.0.0
    - cmake

about:
  home: https://github.com/dmlc/tvm
  license: Apache2
  summary: a low level domain specific language for compiling tensor computation pipelines