if(IS_DIRECTORY ${USE_IMP})
    set(EXTERN_LIBRARY_IMP /home/dut3kor/test/library/build/libImp.so.2.2.0)
    if (EXTERN_LIBRARY_IMP STREQUAL "EXTERN_LIBRARY_IMP-NOTFOUND")
        message(WARNING "Cannot find IMP library at ${USE_IMP}.")
    else()
        tvm_file_glob(GLOB IMP_RELAY_CONTRIB_SRC src/relay/backend/contrib/imp/*.cc)
        list(APPEND COMPILER_SRCS ${IMP_RELAY_CONTRIB_SRC})

        set(IMP_INCLUDE_DIRS ${USE_IMP}/../code/public/include/)
        include_directories(${IMP_INCLUDE_DIRS})
        list(APPEND TVM_RUNTIME_LINKER_LIBS ${EXTERN_LIBRARY_IMP})
        tvm_file_glob(GLOB IMP_CONTRIB_SRC src/runtime/contrib/imp/imp.cc)
        list(APPEND RUNTIME_SRCS ${IMP_CONTRIB_SRC})
        message(STATUS "Build with IMP C source module: " ${EXTERN_LIBRARY_IMP})
    endif()
elseif(USE_IMP STREQUAL "ON")
    tvm_file_glob(GLOB IMP_RELAY_CONTRIB_SRC src/relay/backend/contrib/imp/*.cc)
    list(APPEND COMPILER_SRCS ${IMP_RELAY_CONTRIB_SRC})
  
    # find_library(EXTERN_LIBRARY_IMP imp)
    set(EXTERN_LIBRARY_IMP /home/dut3kor/test/library/build/libImp.so.2.2.0)
    list(APPEND TVM_RUNTIME_LINKER_LIBS ${EXTERN_LIBRARY_IMP})
    set(IMP_INCLUDE_DIRS /home/dut3kor/test/library/code/public/include/)
    include_directories(${IMP_INCLUDE_DIRS})
    tvm_file_glob(GLOB IMP_CONTRIB_SRC src/runtime/contrib/imp/imp.cc)
    list(APPEND RUNTIME_SRCS ${IMP_CONTRIB_SRC})
    message(STATUS "Build with IMP C source module: " ${EXTERN_LIBRARY_IMP})
    
elseif(USE_IMP STREQUAL "OFF")
    # pass
else()
  message(FATAL_ERROR "Invalid option: USE_IMP=" ${USE_IMP})
endif()
