# model_path = "D:\\workspace\\project\\nn_compiler\\tvm\\python\\Deploy"
# model_name = "face_det"
# target_name = "arm_cuda"
# device_name = "tx2"
# dtype = "float16"
# tracker_host = "192.168.6.69"

model_path = "/home/share/data/workspace/project/nn_compiler/tvm/python/depoly"
model_name = "face_det"
target_name = "arm_cuda"
device_name = "tx2"
dtype = "float32"
tracker_host = "192.168.6.252"