[package]
name = "tvm-common"
version = "0.1.0"
authors = ["TVM Contributors"]
license = "Apache-2.0"

[features]
bindings = []

[dependencies]
failure = "0.1.5"
ndarray = "0.12.1"

[build-dependencies]
bindgen = "0.37.4"
