# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""FFI API for Relax."""
# tvm-ffi-stubgen(begin): import-section
# fmt: off
# isort: off
from __future__ import annotations
from tvm_ffi import init_ffi_api as _FFI_INIT_FUNC
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence
    from expr_functor import PyExprMutator, PyExprVisitor
    from ir import Attrs, BaseFunc, DictAttrs, EnvFunc, GlobalVar, IRModule, IntImm, PrimExpr, RelaxExpr, Span, StructInfo, VDevice
    from relax import BlockBuilder, DataflowBlockRewrite, DynTensorType, ExecBuilder, FuncStructInfo, Id, ObjectStructInfo, ObjectType, PackedFuncType, PrimStructInfo, ShapeStructInfo, ShapeType, TensorStructInfo, TupleStructInfo
    from relax.expr import Binding, BindingBlock, Call, Constant, DataTypeImm, DataflowBlock, DataflowVar, ExternFunc, Function, If, MatchCast, PrimValue, SeqExpr, ShapeExpr, StringImm, Tuple, TupleGetItem, Var, VarBinding
    from target import Target
    from te import Tensor
    from tir import Var
    from tvm_ffi import Module, Object, Tensor, dtype
    from typing import Any, Callable
# isort: on
# fmt: on
# tvm-ffi-stubgen(end)


# tvm-ffi-stubgen(begin): global/relax
# fmt: off
_FFI_INIT_FUNC("relax", __name__)
if TYPE_CHECKING:
    def BindingBlock(_0: Sequence[Binding], _1: Span, /) -> BindingBlock: ...
    def BlockBuilderAddFunction(_0: BlockBuilder, _1: BaseFunc, _2: str, /) -> GlobalVar: ...
    def BlockBuilderBeginBindingBlock(_0: BlockBuilder, /) -> None: ...
    def BlockBuilderBeginDataflowBlock(_0: BlockBuilder, /) -> None: ...
    def BlockBuilderBeginScope(_0: BlockBuilder, _1: Sequence[Var] | None, /) -> None: ...
    def BlockBuilderCreate(_0: IRModule | None, /) -> BlockBuilder: ...
    def BlockBuilderCurrentBlockIsDataFlow(_0: BlockBuilder, /) -> bool: ...
    def BlockBuilderEmit(_0: BlockBuilder, _1: RelaxExpr, _2: str, /) -> Var: ...
    def BlockBuilderEmitMatchCast(_0: BlockBuilder, _1: RelaxExpr, _2: StructInfo, _3: str, /) -> Var: ...
    def BlockBuilderEmitNormalized(_0: BlockBuilder, _1: Binding, /) -> None: ...
    def BlockBuilderEmitOutput(_0: BlockBuilder, _1: RelaxExpr, _2: str, /) -> Var: ...
    def BlockBuilderEndBlock(_0: BlockBuilder, /) -> BindingBlock: ...
    def BlockBuilderEndScope(_0: BlockBuilder, /) -> None: ...
    def BlockBuilderFinalize(_0: BlockBuilder, /) -> IRModule: ...
    def BlockBuilderGetContextIRModule(_0: BlockBuilder, /) -> IRModule: ...
    def BlockBuilderGetUniqueName(_0: BlockBuilder, _1: str, /) -> str: ...
    def BlockBuilderLookupBinding(_0: BlockBuilder, _1: Var, /) -> RelaxExpr | None: ...
    def BlockBuilderNormalize(_0: BlockBuilder, _1: RelaxExpr, /) -> RelaxExpr: ...
    def BlockBuilderUpdateFunction(_0: BlockBuilder, _1: GlobalVar, _2: BaseFunc, /) -> None: ...
    def Call(_0: RelaxExpr, _1: Sequence[RelaxExpr], _2: Attrs, _3: Sequence[StructInfo], _4: Span, /) -> Call: ...
    def Constant(_0: Tensor, _1: StructInfo | None, _2: Span, /) -> Constant: ...
    def CopyWithNewVars(_0: Function, /) -> Function: ...
    def DataTypeImm(_0: dtype, _1: Span, /) -> DataTypeImm: ...
    def DataflowBlock(_0: Sequence[Binding], _1: Span, /) -> DataflowBlock: ...
    def DataflowBlockRewrite(_0: DataflowBlock, _1: Function, /) -> DataflowBlockRewrite: ...
    def DataflowVar(_0: str, _1: StructInfo | None, _2: Span, /) -> DataflowVar: ...
    def DataflowVarFromId(_0: Id, _1: StructInfo | None, _2: Span, /) -> DataflowVar: ...
    def ExecBuilderC(_0: ExecBuilder, _1: int, /) -> int: ...
    def ExecBuilderConvertConstant(*args: Any) -> Any: ...
    def ExecBuilderCreate() -> ExecBuilder: ...
    def ExecBuilderDeclareFunction(_0: ExecBuilder, _1: str, _2: int, /) -> None: ...
    def ExecBuilderEmitCall(_0: ExecBuilder, _1: str, _2: Sequence[IntImm], _3: int, /) -> None: ...
    def ExecBuilderEmitFunction(_0: ExecBuilder, _1: str, _2: int, _3: Sequence[str] | None, /) -> None: ...
    def ExecBuilderEmitGoto(_0: ExecBuilder, _1: int, /) -> None: ...
    def ExecBuilderEmitIf(_0: ExecBuilder, _1: int, _2: int, /) -> None: ...
    def ExecBuilderEmitRet(_0: ExecBuilder, _1: int, /) -> None: ...
    def ExecBuilderEndFunction(_0: ExecBuilder, _1: str, /) -> None: ...
    def ExecBuilderF(_0: ExecBuilder, _1: str, /) -> int: ...
    def ExecBuilderGet(_0: ExecBuilder, /) -> Module: ...
    def ExecBuilderImm(_0: ExecBuilder, _1: int, /) -> int: ...
    def ExecBuilderR(_0: ExecBuilder, _1: int, /) -> int: ...
    def ExecutableLoadFromFile(_0: str, /) -> Module: ...
    def ExprMutatorVisitBinding(_0: PyExprMutator, _1: Binding, /) -> None: ...
    def ExprMutatorVisitBindingBlock(_0: PyExprMutator, _1: BindingBlock, /) -> BindingBlock: ...
    def ExprMutatorVisitExpr(_0: PyExprMutator, _1: RelaxExpr, /) -> RelaxExpr: ...
    def ExprMutatorVisitVarDef(_0: PyExprMutator, _1: Var, /) -> Var: ...
    def ExprVisitorVisitBinding(_0: PyExprVisitor, _1: Binding, /) -> None: ...
    def ExprVisitorVisitBindingBlock(_0: PyExprVisitor, _1: BindingBlock, /) -> None: ...
    def ExprVisitorVisitExpr(_0: PyExprVisitor, _1: RelaxExpr, /) -> None: ...
    def ExprVisitorVisitSpan(_0: PyExprVisitor, _1: Span, /) -> None: ...
    def ExprVisitorVisitVarDef(_0: PyExprVisitor, _1: Var, /) -> None: ...
    def ExternFunc(_0: str, _1: StructInfo | None, _2: Span, /) -> ExternFunc: ...
    def FuncStructInfo(_0: Sequence[StructInfo], _1: StructInfo, _2: bool, _3: Span, /) -> FuncStructInfo: ...
    def FuncStructInfoOpaqueFunc(_0: StructInfo | None, _1: EnvFunc | None, _2: bool, _3: Span, /) -> FuncStructInfo: ...
    def FuncWithAttr(_0: BaseFunc, _1: str, _2: Object, /) -> Function | None: ...
    def FuncWithAttrs(_0: BaseFunc, _1: Mapping[str, Any], /) -> Function | None: ...
    def FuncWithoutAttr(_0: BaseFunc, _1: str, /) -> Function | None: ...
    def Function(_0: Sequence[Var], _1: RelaxExpr, _2: StructInfo | None, _3: bool, _4: DictAttrs, _5: Span, /) -> Function: ...
    def FunctionBindParams(_0: Function, _1: Mapping[Any, Object], /) -> Function: ...
    def FunctionBindSymbolicVars(_0: Function, _1: Mapping[Var | str, PrimExpr], /) -> Function: ...
    def FunctionCreateEmpty(_0: Sequence[Var], _1: StructInfo, _2: bool, _3: DictAttrs, _4: Span, /) -> Function: ...
    def FunctionInlineFunctions(_0: Function, _1: Mapping[str | GlobalVar, Function], /) -> Function: ...
    def GetShapeOf(_0: RelaxExpr, /) -> RelaxExpr: ...
    def If(_0: RelaxExpr, _1: RelaxExpr, _2: RelaxExpr, _3: Span, /) -> If: ...
    def MakePyExprMutator(_0: BlockBuilder, _1: Callable[..., Any], _2: Callable[..., Any], _3: Callable[..., Any], _4: Callable[..., Any], _5: Callable[..., Any], _6: Callable[..., Any], _7: Callable[..., Any], _8: Callable[..., Any], _9: Callable[..., Any], _10: Callable[..., Any], _11: Callable[..., Any], _12: Callable[..., Any], _13: Callable[..., Any], _14: Callable[..., Any], _15: Callable[..., Any], _16: Callable[..., Any], _17: Callable[..., Any], _18: Callable[..., Any], _19: Callable[..., Any], _20: Callable[..., Any], _21: Callable[..., Any], _22: Callable[..., Any], _23: Callable[..., Any], _24: Callable[..., Any], _25: Callable[..., Any], _26: Callable[..., Any], _27: Callable[..., Any], /) -> PyExprMutator: ...
    def MakePyExprVisitor(_0: Callable[..., Any], _1: Callable[..., Any], _2: Callable[..., Any], _3: Callable[..., Any], _4: Callable[..., Any], _5: Callable[..., Any], _6: Callable[..., Any], _7: Callable[..., Any], _8: Callable[..., Any], _9: Callable[..., Any], _10: Callable[..., Any], _11: Callable[..., Any], _12: Callable[..., Any], _13: Callable[..., Any], _14: Callable[..., Any], _15: Callable[..., Any], _16: Callable[..., Any], _17: Callable[..., Any], _18: Callable[..., Any], _19: Callable[..., Any], _20: Callable[..., Any], _21: Callable[..., Any], _22: Callable[..., Any], _23: Callable[..., Any], _24: Callable[..., Any], _25: Callable[..., Any], _26: Callable[..., Any], /) -> PyExprVisitor: ...
    def MatchCast(_0: Var, _1: RelaxExpr, _2: StructInfo, _3: Span, /) -> MatchCast: ...
    def ObjectStructInfo(_0: Span, /) -> ObjectStructInfo: ...
    def ObjectType(_0: Span, /) -> ObjectType: ...
    def PackedFuncType(_0: Span, /) -> PackedFuncType: ...
    def PrimStructInfoFromDtype(_0: dtype, _1: Span, /) -> PrimStructInfo: ...
    def PrimStructInfoFromValue(_0: PrimExpr, _1: Span, /) -> PrimStructInfo: ...
    def PrimValue(_0: PrimExpr, _1: Span, /) -> PrimValue: ...
    def PyExprMutatorGetVarRemap(_0: PyExprMutator, _1: Id, /) -> Var: ...
    def PyExprMutatorLookupBinding(_0: PyExprMutator, _1: Var, /) -> RelaxExpr | None: ...
    def PyExprMutatorSetVarRemap(_0: PyExprMutator, _1: Id, _2: Var, /) -> Var: ...
    def PyExprMutatorVisitBinding(_0: PyExprMutator, _1: Binding, /) -> None: ...
    def PyExprMutatorVisitBindingBlock(_0: PyExprMutator, _1: BindingBlock, /) -> BindingBlock: ...
    def PyExprMutatorVisitExpr(_0: PyExprMutator, _1: RelaxExpr, /) -> RelaxExpr: ...
    def PyExprMutatorVisitExprPostOrder(_0: PyExprMutator, _1: RelaxExpr, /) -> RelaxExpr: ...
    def PyExprMutatorVisitVarDef(_0: PyExprMutator, _1: Var, /) -> Var: ...
    def PyExprMutatorVisitWithNewScope(_0: PyExprMutator, _1: RelaxExpr, /) -> RelaxExpr: ...
    def PyExprMutatorWithStructInfo(_0: PyExprMutator, _1: Var, _2: StructInfo, /) -> Var: ...
    def PyExprVisitorVisitBinding(_0: PyExprVisitor, _1: Binding, /) -> None: ...
    def PyExprVisitorVisitBindingBlock(_0: PyExprVisitor, _1: BindingBlock, /) -> None: ...
    def PyExprVisitorVisitExpr(_0: PyExprVisitor, _1: RelaxExpr, /) -> None: ...
    def PyExprVisitorVisitVarDef(_0: PyExprVisitor, _1: Var, /) -> None: ...
    def SeqExpr(_0: Sequence[BindingBlock], _1: RelaxExpr, _2: Span, /) -> SeqExpr: ...
    def ShapeExpr(_0: Sequence[PrimExpr], _1: Span, /) -> ShapeExpr: ...
    def ShapeStructInfo(_0: Sequence[PrimExpr] | None, _1: int, _2: Span, /) -> ShapeStructInfo: ...
    def ShapeType(_0: int, _1: Span, /) -> ShapeType: ...
    def StringImm(_0: str, _1: Span, /) -> StringImm: ...
    def StructInfoIsBaseOf(_0: StructInfo, _1: StructInfo, /) -> bool: ...
    def TETensor(_0: RelaxExpr, _1: Mapping[Var, PrimExpr], _2: str, /) -> Tensor: ...
    def TensorStructInfo(_0: RelaxExpr | None, _1: dtype | None, _2: int, _3: VDevice, _4: Span, /) -> TensorStructInfo: ...
    def TensorType(_0: int, _1: dtype, _2: Span, /) -> DynTensorType: ...
    def Tuple(_0: Sequence[RelaxExpr], _1: Span, /) -> Tuple: ...
    def TupleGetItem(_0: RelaxExpr, _1: int, _2: Span, /) -> TupleGetItem: ...
    def TupleStructInfo(_0: Sequence[StructInfo], _1: Span, /) -> TupleStructInfo: ...
    def UpdateStructInfo(_0: RelaxExpr, _1: StructInfo, /) -> None: ...
    def VMCodeGen(_0: ExecBuilder, _1: IRModule, /) -> IRModule: ...
    def VMLink(_0: ExecBuilder, _1: Target, _2: Module | None, _3: Sequence[Module], _4: Mapping[str, Tensor], /) -> Module: ...
    def VMTIRCodeGen(_0: ExecBuilder, _1: IRModule, /) -> IRModule: ...
    def Var(_0: str, _1: StructInfo | None, _2: Span, /) -> Var: ...
    def VarBinding(_0: Var, _1: RelaxExpr, _2: Span, /) -> VarBinding: ...
    def VarFromId(_0: Id, _1: StructInfo | None, _2: Span, /) -> Var: ...
    def dfb_rewrite_add(_0: DataflowBlockRewrite, _1: RelaxExpr, _2: str | None, _3: bool, /) -> None: ...
    def dfb_rewrite_add_binding(_0: DataflowBlockRewrite, _1: Binding, /) -> None: ...
    def dfb_rewrite_mutate_irmodule(_0: DataflowBlockRewrite, _1: IRModule, /) -> IRModule: ...
    def dfb_rewrite_remove_all_unused(_0: DataflowBlockRewrite, /) -> None: ...
    def dfb_rewrite_remove_unused(_0: DataflowBlockRewrite, _1: Var, _2: bool, /) -> None: ...
    def dfb_rewrite_replace_all_uses(_0: DataflowBlockRewrite, _1: Var, _2: Var, /) -> None: ...
# fmt: on
# tvm-ffi-stubgen(end)
