# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# ruff: noqa: F841
"""S-TIR script ir builder."""

import tvm
import tvm.runtime
import tvm.testing
from tvm import s_tir, tirx
from tvm.ir.base import SourceName, Span, assert_structural_equal
from tvm.s_tir.script.ir_builder import prim_func as build_prim_func
from tvm.script import s_tir as Ts
from tvm.script.ir_builder import IRBuilder
from tvm.tirx.script import ir_builder as T


def test_ir_builder_tir_primfunc_base():
    with IRBuilder() as ib:
        with build_prim_func():
            T.evaluate(0)

    # the prim_func generated by IRBuilder
    prim_func_actual = ib.get()

    # the expected prim_func
    prim_func_expected = tirx.PrimFunc(
        params=[],
        body=tirx.Evaluate(0),
        ret_type=None,
        attrs=tvm.ir.make_node("ir.DictAttrs", **{"s_tir": True}),
    )

    # Check if the generated ir is expected
    assert_structural_equal(prim_func_actual, prim_func_expected, map_free_vars=True)


def test_ir_builder_source_span_applies_to_emitted_stmt():
    span = Span(SourceName("builder_test.py"), 7, 7, 5, 18)
    with IRBuilder() as ib:
        with build_prim_func():
            with ib.with_source_span(span):
                T.evaluate(1)

    actual = ib.get().body.span
    assert actual.source_name.name == "builder_test.py"
    assert (actual.line, actual.column, actual.end_line, actual.end_column) == (7, 5, 7, 18)


def test_ir_builder_tir_primfunc_complete():
    with IRBuilder() as ib:
        with build_prim_func():
            T.arg_("a", T.handle())
            T.arg_("b", T.int64())
            T.arg_("c", T.Buffer((128, 128), "float32"))
            buffer_d = T.arg_("d", T.Buffer((64, 64), "int64"))
            e = T.arg_("e", T.Buffer((1024,), "int8"))
            T.func_attr({"key": "value"})
            T.func_ret(tvm.ir.PrimType("int64"))

            T.evaluate(0)

    # the prim_func generated by IRBuilder
    prim_func_actual = ib.get()

    # the expected prim_func
    c_buffer = tirx.decl_buffer((128, 128), "float32", name="c", layout=None)
    d_buffer = tirx.decl_buffer((64, 64), "int64", name="d", layout=None)
    e_buffer = tirx.decl_buffer((1024,), "int8", name="e", layout=None)
    prim_func_expected = tirx.PrimFunc(
        params=[
            tirx.Var("a", tvm.ir.PointerType(tvm.ir.PrimType("void"))),
            tirx.Var("b", "int64"),
            c_buffer,
            d_buffer,
            e_buffer,
        ],
        body=tirx.Evaluate(0),
        ret_type=tvm.ir.PrimType("int64"),
        attrs=tvm.ir.make_node("ir.DictAttrs", **{"key": "value", "s_tir": True}),
    )

    # Check if the generated ir is expected
    assert_structural_equal(prim_func_actual, prim_func_expected, map_free_vars=True)


def test_ir_builder_tir_block_base():
    with IRBuilder() as ib:
        with Ts.sblock("block"):
            T.evaluate(0)

    # the block generated by IRBuilder
    block_realize_actual = ib.get()

    # the expected block
    block_expected = s_tir.SBlock(
        iter_vars=[],
        reads=[],
        writes=[],
        name_hint="block",
        body=tirx.Evaluate(0),
        alloc_buffers=None,
        match_buffers=None,
        annotations={"tirx.script_parsing_detect_access": tirx.IntImm("int64", 3)},
    )
    block_realize_expected = s_tir.SBlockRealize(
        iter_values=[],
        predicate=True,
        block=block_expected,
    )

    # Check if the generated ir is expected
    assert_structural_equal(block_realize_actual, block_realize_expected, map_free_vars=True)


def test_ir_builder_tir_block_complete():
    with IRBuilder() as ib:
        a = T.int64()
        b = T.Buffer((128, 128), "float32")
        c = T.Buffer((128, 128), "float32")
        d = T.int32()
        e = T.Buffer((128, 128), "float32")
        f = T.int32()
        with Ts.sblock("block"):
            Ts.where(a > 1)
            Ts.reads(b[0:16, 0:16])
            Ts.writes(c[d:128, d:128])
            Ts.sblock_attr({"key": "value"})
            Ts.sblock_alloc_buffer((128, 128), "float32")
            Ts.match_buffer(e[0:32, 0:32], (32, 32), "float32")
            Ts.axis.spatial(128, f)
            T.evaluate(0)

    # the block generated by IRBuilder
    block_realize_actual = ib.get()

    # the expected block
    var_a = tirx.Var("a", "int64")
    buffer_b = tirx.decl_buffer((128, 128), "float32", name="b")
    buffer_c = tirx.decl_buffer((128, 128), "float32", name="c")
    var_d = tirx.Var("d", "int32")
    buffer_e = tirx.decl_buffer((128, 128), "float32", name="c")
    var_f = tirx.Var("f", "int32")
    block_expected = s_tir.SBlock(
        iter_vars=[tirx.IterVar((0, 128), tirx.Var("", "int32"), iter_type=tirx.IterVar.DataPar)],
        reads=[buffer_b[0:16, 0:16]],
        writes=[buffer_c[var_d:128, var_d:128]],
        name_hint="block",
        body=tirx.Evaluate(0),
        alloc_buffers=[tirx.decl_buffer((128, 128), "float32")],
        match_buffers=[
            s_tir.MatchBufferRegion(tirx.decl_buffer((32, 32), "float32"), buffer_e[0:32, 0:32])
        ],
        annotations={"key": "value"},
    )
    block_realize_expected = s_tir.SBlockRealize(
        iter_values=[var_f],
        predicate=var_a > 1,
        block=block_expected,
    )

    # Check if the generated ir is expected
    assert_structural_equal(block_realize_actual, block_realize_expected, map_free_vars=True)


def test_ir_builder_tir_axis():
    with IRBuilder() as ib:
        a = T.int32()
        b = T.int32()
        c = T.int32()
        d = T.int32()
        with Ts.sblock("block"):
            Ts.axis.spatial(8, a)
            Ts.axis.reduce(16, b)
            Ts.axis.scan(32, c)
            Ts.axis.opaque(64, d)
            T.evaluate(0)

    # the block generated by IRBuilder
    block_realize_actual = ib.get()

    # the expected block
    var_a = tirx.Var("a", "int32")
    var_b = tirx.Var("b", "int32")
    var_c = tirx.Var("c", "int32")
    var_d = tirx.Var("d", "int32")
    block_expected = s_tir.SBlock(
        iter_vars=[
            tirx.IterVar((0, 8), tirx.Var("", "int32"), iter_type=tirx.IterVar.DataPar),
            tirx.IterVar((0, 16), tirx.Var("", "int32"), iter_type=tirx.IterVar.CommReduce),
            tirx.IterVar((0, 32), tirx.Var("", "int32"), iter_type=tirx.IterVar.Ordered),
            tirx.IterVar((0, 64), tirx.Var("", "int32"), iter_type=tirx.IterVar.Opaque),
        ],
        reads=[],
        writes=[],
        name_hint="block",
        body=tirx.Evaluate(0),
        annotations={"tirx.script_parsing_detect_access": tirx.IntImm("int64", 3)},
    )
    block_realize_expected = s_tir.SBlockRealize(
        iter_values=[var_a, var_b, var_c, var_d],
        predicate=True,
        block=block_expected,
    )

    # Check if the generated ir is expected
    assert_structural_equal(block_realize_actual, block_realize_expected, map_free_vars=True)


def test_ir_builder_tir_thread():
    with IRBuilder() as ib:
        with build_prim_func():
            brow = T.env_thread("blockIdx.y")
            with T.launch_thread(brow, 1):
                T.evaluate(0)

    # the prim_func generated by IRBuilder
    ir_actual = ib.get()

    # the expected prim_func
    iter_var = tirx.IterVar((0, 1), "v", iter_type=1, thread_tag="blockIdx.y")
    attr_stmt = tirx.AttrStmt(iter_var, "thread_extent", 1, tirx.Evaluate(0))
    func = tirx.PrimFunc([], attr_stmt).with_attr("s_tir", True)

    # Check if the generated ir is expected
    assert_structural_equal(ir_actual, func, map_free_vars=True)


def test_ir_builder_tir_allocate():
    with IRBuilder() as ib:
        with build_prim_func():
            T.func_name_("test")
            buf = T.alloc_buffer([10], "float32", scope="local")
            T.evaluate(1)

    # the allocate generated by IRBuilder
    ir_actual = ib.get()
    body = ir_actual.body

    # AllocBuffer is flat: body should be a SeqStmt with [AllocBuffer, Evaluate(1)]
    assert isinstance(body, tirx.SeqStmt), f"Expected SeqStmt but got {type(body)}"
    assert len(body) == 2
    assert isinstance(body[0], tirx.AllocBuffer)
    assert isinstance(body[1], tirx.Evaluate)
    assert body[1].value.value == 1


def test_ir_builder_tir_decl_buffer():
    with IRBuilder() as ib:
        with build_prim_func():
            T.func_name_("test")
            buf = T.decl_buffer([128, 128], "float32")
            T.evaluate(1)

    # the decl_buffer generated by IRBuilder
    ir_actual = ib.get()
    body = ir_actual.body

    # decl_buffer without data emits AllocBuffer (flat): body should be SeqStmt
    assert isinstance(body, tirx.SeqStmt), f"Expected SeqStmt but got {type(body)}"
    assert len(body) == 2
    assert isinstance(body[0], tirx.AllocBuffer)
    assert isinstance(body[1], tirx.Evaluate)
    assert body[1].value.value == 1


if __name__ == "__main__":
    tvm.testing.main()
