# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# pylint: disable=unused-import, redefined-builtin
"""Namespace for Tensor-level IR"""

from tvm.ir import PrimExpr
from tvm.runtime import const

from . import analysis, backend, stmt_functor, transform
from .buffer import Buffer, DataProducer, decl_buffer
from .build import build
from .expr import (
    EQ,
    GE,
    GT,
    LE,
    LT,
    NE,
    Add,
    And,
    Broadcast,
    BufferLoad,
    Call,
    CallEffectKind,
    Cast,
    CommReducer,
    Div,
    FloatImm,
    FloorDiv,
    FloorMod,
    IntImm,
    IterVar,
    Let,
    Max,
    Min,
    Mod,
    Mul,
    Not,
    Or,
    ProducerLoad,
    Ramp,
    Reduce,
    Select,
    Shuffle,
    SizeVar,
    StringImm,
    Sub,
    Var,
    convert,
)
from .function import IndexMap, PrimFunc, TensorIntrin
from .functor import PyStmtExprMutator, PyStmtExprVisitor
from .generic import add, multiply, subtract
from .op import (
    TVMBackendAllocWorkspace,
    TVMBackendFreeWorkspace,
    abs,
    acos,
    acosh,
    address_of,
    all,
    any,
    asin,
    asinh,
    assume,
    atan,
    atan2,
    atanh,
    bitwise_and,
    bitwise_not,
    bitwise_or,
    bitwise_xor,
    break_loop,
    call_cpacked,
    call_cpacked_lowered,
    call_extern,
    call_intrin,
    call_llvm_intrin,
    call_llvm_pure_intrin,
    call_packed,
    call_packed_lowered,
    call_pure_extern,
    call_tir,
    ceil,
    ceildiv,
    clz,
    comm_reducer,
    continue_loop,
    copysign,
    cos,
    cosh,
    create_barriers,
    div,
    dp4a,
    end_profile_intrinsic,
    erf,
    exp,
    exp2,
    exp10,
    floor,
    floordiv,
    floormod,
    fmod,
    get_active_lane_mask,
    get_vscale_expr,
    handle_add_byte_offset,
    hypot,
    if_then_else,
    ignore_loop_partition,
    indexdiv,
    indexmod,
    infinity,
    isfinite,
    isinf,
    isnan,
    isnullptr,
    ldexp,
    likely,
    log,
    log1p,
    log2,
    log10,
    logaddexp,
    lookup_param,
    make_filled_simdgroup_matrix,
    max,
    max_value,
    min,
    min_value,
    mma_fill,
    mma_store,
    nearbyint,
    nextafter,
    popcount,
    pow,
    power,
    ptx_arrive_barrier,
    ptx_arrive_barrier_expect_tx,
    ptx_commit_group,
    ptx_cp_async,
    ptx_cp_async_barrier,
    ptx_cp_async_bulk,
    ptx_init_barrier_thread_count,
    ptx_ldmatrix,
    ptx_mma,
    ptx_mma_sp,
    ptx_wait_barrier,
    ptx_wait_group,
    q_multiply_shift,
    q_multiply_shift_per_axis,
    reinterpret,
    ret,
    round,
    rsqrt,
    shift_left,
    shift_right,
    sigmoid,
    simdgroup_load,
    simdgroup_multiply_accumulate,
    simdgroup_store,
    sin,
    sinh,
    sqrt,
    start_profile_intrinsic,
    sum,
    tan,
    tanh,
    trace,
    trunc,
    truncdiv,
    truncmod,
    tvm_access_ptr,
    tvm_bmma_sync,
    tvm_fill_fragment,
    tvm_load_matrix_sync,
    tvm_mma_sync,
    tvm_stack_alloca,
    tvm_stack_make_array,
    tvm_stack_make_shape,
    tvm_store_matrix_sync,
    tvm_struct_get,
    tvm_struct_set,
    tvm_thread_allreduce,
    tvm_throw_last_error,
    tvm_tuple,
    type_annotation,
    undef,
    vectorcombine,
    vectorhigh,
    vectorlow,
    vscale,
)
from .pipeline import get_default_tir_pipeline, get_tir_pipeline
from .stmt import (
    Allocate,
    AssertStmt,
    AttrStmt,
    BufferRegion,
    BufferStore,
    DeclBuffer,
    Evaluate,
    For,
    ForKind,
    IfThenElse,
    LetStmt,
    MatchBufferRegion,
    SBlock,
    SBlockRealize,
    SeqStmt,
    Stmt,
    While,
    stmt_list,
    stmt_seq,
)
