# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""FFI APIs for tvm.tir"""
# tvm-ffi-stubgen(begin): import-section
# fmt: off
# isort: off
from __future__ import annotations
from tvm_ffi import init_ffi_api as _FFI_INIT_FUNC
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence
    from ir import DictAttrs, IRModule, PrimExpr, Range, RelaxExpr, Span, Type
    from tir import Add, Allocate, AllocateConst, And, AssertStmt, AttrStmt, BijectiveLayout, Block, BlockDependenceInfo, BlockRealize, BlockScope, Broadcast, Buffer, BufferLoad, BufferRealize, BufferRegion, BufferStore, Call, Cast, CommReducer, DataProducer, DeclBuffer, Dependency, Div, EQ, Evaluate, FloorDiv, FloorMod, For, GE, GT, IfThenElse, IndexMap, IterVar, LE, LT, Layout, Let, LetStmt, MatchBufferRegion, Max, Min, Mod, Mul, NE, Not, Or, PrimFunc, ProducerLoad, PyStmtExprMutator, PyStmtExprVisitor, Ramp, Reduce, Select, SeqStmt, Shuffle, SizeVar, Stmt, StmtSRef, StringImm, Sub, TensorIntrin, Var, While
    from tvm_ffi import Object, Tensor, dtype
    from typing import Any, Callable
# isort: on
# fmt: on
# tvm-ffi-stubgen(end)



# tvm-ffi-stubgen(begin): global/tir
# fmt: off
_FFI_INIT_FUNC("tir", __name__)
if TYPE_CHECKING:
    def Add(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> Add: ...
    def Allocate(_0: Var, _1: dtype, _2: Sequence[PrimExpr], _3: PrimExpr, _4: Stmt, _5: Mapping[str, Any], _6: Span, /) -> Allocate: ...
    def AllocateConst(_0: Var, _1: dtype, _2: Sequence[PrimExpr], _3: Object, _4: Stmt, _5: Mapping[str, Any] | None, _6: Span, /) -> AllocateConst: ...
    def And(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> And: ...
    def AssertStmt(_0: PrimExpr, _1: StringImm, _2: Stmt, _3: Span, /) -> AssertStmt: ...
    def AttrStmt(_0: Any, _1: str, _2: PrimExpr, _3: Stmt, _4: Span, /) -> AttrStmt: ...
    def BijectiveLayout(_0: Layout, _1: Layout, /) -> BijectiveLayout: ...
    def BijectiveLayoutBackwardIndex(_0: BijectiveLayout, _1: Sequence[PrimExpr], /) -> Sequence[PrimExpr]: ...
    def BijectiveLayoutBackwardShape(_0: BijectiveLayout, _1: Sequence[PrimExpr], /) -> Sequence[PrimExpr]: ...
    def BijectiveLayoutForwardIndex(_0: BijectiveLayout, _1: Sequence[PrimExpr], /) -> Sequence[PrimExpr]: ...
    def BijectiveLayoutForwardShape(_0: BijectiveLayout, _1: Sequence[PrimExpr], /) -> Sequence[PrimExpr]: ...
    def Block(_0: Sequence[IterVar], _1: Sequence[BufferRegion], _2: Sequence[BufferRegion], _3: str, _4: Stmt, _5: Stmt | None, _6: Sequence[Buffer], _7: Sequence[MatchBufferRegion], _8: Mapping[str, Any], _9: Span, /) -> Block: ...
    def BlockDependenceInfo(_0: IRModule, /) -> BlockDependenceInfo: ...
    def BlockDependenceInfoGetBlockScope(_0: BlockDependenceInfo, _1: StmtSRef, /) -> BlockScope: ...
    def BlockDependenceInfoGetSRef(_0: BlockDependenceInfo, _1: Stmt, /) -> StmtSRef | None: ...
    def BlockRealize(_0: Sequence[PrimExpr], _1: PrimExpr, _2: Block, _3: Span, /) -> BlockRealize: ...
    def BlockScopeGetDepsByDst(_0: BlockScope, _1: StmtSRef, /) -> Sequence[Dependency]: ...
    def BlockScopeGetDepsBySrc(_0: BlockScope, _1: StmtSRef, /) -> Sequence[Dependency]: ...
    def Broadcast(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> Broadcast: ...
    def Buffer(*args: Any) -> Any: ...
    def BufferAccessPtr(_0: Buffer, _1: int, _2: dtype, _3: int, _4: PrimExpr, _5: PrimExpr | None, /) -> PrimExpr: ...
    def BufferGetFlattenedBuffer(_0: Buffer, /) -> Buffer: ...
    def BufferLoad(_0: Buffer, _1: Sequence[PrimExpr], _2: PrimExpr | None, _3: Span, /) -> BufferLoad: ...
    def BufferOffsetOf(_0: Buffer, _1: Sequence[PrimExpr], /) -> Sequence[PrimExpr]: ...
    def BufferRealize(_0: Buffer, _1: Sequence[Range], _2: PrimExpr, _3: Stmt, _4: Span, /) -> BufferRealize: ...
    def BufferRegion(_0: Buffer, _1: Sequence[Range], /) -> BufferRegion: ...
    def BufferStorageScope(_0: Buffer, /) -> str: ...
    def BufferStore(_0: Buffer, _1: PrimExpr, _2: Sequence[PrimExpr], _3: PrimExpr | None, _4: Span, /) -> BufferStore: ...
    def BufferVLoad(_0: Buffer, _1: Sequence[PrimExpr], _2: dtype, _3: PrimExpr | None, /) -> PrimExpr: ...
    def BufferVStore(_0: Buffer, _1: Sequence[PrimExpr], _2: PrimExpr, _3: PrimExpr | None, /) -> Stmt: ...
    def Call(_0: dtype | None, _1: RelaxExpr, _2: Sequence[str | dtype | IterVar | BufferRegion | PrimExpr], _3: Span, /) -> Call: ...
    def Cast(_0: dtype, _1: PrimExpr, _2: Span, /) -> Cast: ...
    def CommReducer(_0: Sequence[Var], _1: Sequence[Var], _2: Sequence[PrimExpr], _3: Sequence[PrimExpr], _4: Span, /) -> CommReducer: ...
    def CommReducerCombine(_0: CommReducer, _1: Sequence[PrimExpr], _2: Sequence[PrimExpr], /) -> Sequence[PrimExpr]: ...
    def DeclBuffer(_0: Buffer, _1: Stmt, _2: Span, /) -> DeclBuffer: ...
    def Div(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> Div: ...
    def EQ(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> EQ: ...
    def Evaluate(_0: PrimExpr, _1: Span, /) -> Evaluate: ...
    def FloorDiv(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> FloorDiv: ...
    def FloorMod(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> FloorMod: ...
    def For(_0: Var, _1: PrimExpr, _2: PrimExpr, _3: int, _4: Stmt, _5: IterVar | None, _6: Mapping[str, Any] | None, _7: PrimExpr | None, _8: Span, /) -> For: ...
    def GE(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> GE: ...
    def GT(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> GT: ...
    def IRTransform(_0: Stmt, _1: Callable[..., Any], _2: Callable[..., Any], _3: Sequence[str] | None, /) -> Stmt: ...
    def IfThenElse(_0: PrimExpr, _1: Stmt, _2: Stmt, _3: Span, /) -> IfThenElse: ...
    def IndexMap(_0: Sequence[Var], _1: Sequence[PrimExpr], _2: IndexMap | None, /) -> IndexMap: ...
    def IndexMapInverse(_0: IndexMap, _1: Sequence[Range], /) -> IndexMap: ...
    def IndexMapMapIndices(_0: IndexMap, _1: Sequence[PrimExpr], /) -> Sequence[PrimExpr]: ...
    def IndexMapMapShape(_0: IndexMap, _1: Sequence[PrimExpr], /) -> Sequence[PrimExpr]: ...
    def IndexMapMapTensor(_0: IndexMap, _1: Tensor, /) -> Tensor: ...
    def IndexMapNonSurjectiveInverse(_0: IndexMap, _1: Sequence[Range], /) -> Sequence[Object]: ...
    def IterVar(_0: Range, _1: Var, _2: int, _3: str, _4: Span, /) -> IterVar: ...
    def LE(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> LE: ...
    def LT(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> LT: ...
    def Layout(_0: str, _1: dtype, /) -> Layout: ...
    def LayoutFactorOf(_0: Layout, _1: str, /) -> int: ...
    def LayoutGetItem(_0: Layout, _1: int, /) -> str: ...
    def LayoutIndexOf(_0: Layout, _1: str, /) -> int: ...
    def LayoutNdim(_0: Layout, /) -> int: ...
    def Let(_0: Var, _1: PrimExpr, _2: PrimExpr, _3: Span, /) -> Let: ...
    def LetStmt(_0: Var, _1: PrimExpr, _2: Stmt, _3: Span, /) -> LetStmt: ...
    def MakePyStmtExprMutator(_0: Callable[..., Any], _1: Callable[..., Any], _2: Callable[..., Any], _3: Callable[..., Any], _4: Callable[..., Any], _5: Callable[..., Any], _6: Callable[..., Any], _7: Callable[..., Any], _8: Callable[..., Any], _9: Callable[..., Any], _10: Callable[..., Any], _11: Callable[..., Any], _12: Callable[..., Any], _13: Callable[..., Any], _14: Callable[..., Any], _15: Callable[..., Any], _16: Callable[..., Any], _17: Callable[..., Any], _18: Callable[..., Any], _19: Callable[..., Any], _20: Callable[..., Any], _21: Callable[..., Any], _22: Callable[..., Any], _23: Callable[..., Any], _24: Callable[..., Any], _25: Callable[..., Any], _26: Callable[..., Any], _27: Callable[..., Any], _28: Callable[..., Any], _29: Callable[..., Any], _30: Callable[..., Any], _31: Callable[..., Any], _32: Callable[..., Any], _33: Callable[..., Any], _34: Callable[..., Any], _35: Callable[..., Any], _36: Callable[..., Any], _37: Callable[..., Any], _38: Callable[..., Any], _39: Callable[..., Any], _40: Callable[..., Any], _41: Callable[..., Any], _42: Callable[..., Any], _43: Callable[..., Any], _44: Callable[..., Any], _45: Callable[..., Any], _46: Callable[..., Any], _47: Callable[..., Any], _48: Callable[..., Any], _49: Callable[..., Any], /) -> PyStmtExprMutator: ...
    def MakePyStmtExprVisitor(_0: Callable[..., Any], _1: Callable[..., Any], _2: Callable[..., Any], _3: Callable[..., Any], _4: Callable[..., Any], _5: Callable[..., Any], _6: Callable[..., Any], _7: Callable[..., Any], _8: Callable[..., Any], _9: Callable[..., Any], _10: Callable[..., Any], _11: Callable[..., Any], _12: Callable[..., Any], _13: Callable[..., Any], _14: Callable[..., Any], _15: Callable[..., Any], _16: Callable[..., Any], _17: Callable[..., Any], _18: Callable[..., Any], _19: Callable[..., Any], _20: Callable[..., Any], _21: Callable[..., Any], _22: Callable[..., Any], _23: Callable[..., Any], _24: Callable[..., Any], _25: Callable[..., Any], _26: Callable[..., Any], _27: Callable[..., Any], _28: Callable[..., Any], _29: Callable[..., Any], _30: Callable[..., Any], _31: Callable[..., Any], _32: Callable[..., Any], _33: Callable[..., Any], _34: Callable[..., Any], _35: Callable[..., Any], _36: Callable[..., Any], _37: Callable[..., Any], _38: Callable[..., Any], _39: Callable[..., Any], _40: Callable[..., Any], _41: Callable[..., Any], _42: Callable[..., Any], _43: Callable[..., Any], _44: Callable[..., Any], _45: Callable[..., Any], _46: Callable[..., Any], _47: Callable[..., Any], _48: Callable[..., Any], _49: Callable[..., Any], /) -> PyStmtExprVisitor: ...
    def MatchBufferRegion(_0: Buffer, _1: BufferRegion, /) -> MatchBufferRegion: ...
    def Max(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> Max: ...
    def Min(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> Min: ...
    def Mod(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> Mod: ...
    def Mul(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> Mul: ...
    def NE(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> NE: ...
    def Not(_0: PrimExpr, _1: Span, /) -> Not: ...
    def Or(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> Or: ...
    def PostOrderVisit(_0: Object, _1: Callable[..., Any], /) -> None: ...
    def PreOrderVisit(_0: Object, _1: Callable[..., Any], /) -> None: ...
    def PrimFunc(_0: Sequence[Var], _1: Stmt, _2: Type, _3: Mapping[Var, Buffer], _4: DictAttrs, _5: Span, /) -> PrimFunc: ...
    def ProducerLoad(_0: DataProducer, _1: Sequence[PrimExpr], _2: Span, /) -> ProducerLoad: ...
    def PyStmtExprMutatorDefaultVisitExpr(_0: PyStmtExprMutator, _1: PrimExpr, /) -> None: ...
    def PyStmtExprMutatorDefaultVisitStmt(_0: PyStmtExprMutator, _1: Stmt, /) -> None: ...
    def PyStmtExprMutatorVisitExpr(_0: PyStmtExprMutator, _1: PrimExpr, /) -> PrimExpr: ...
    def PyStmtExprMutatorVisitStmt(_0: PyStmtExprMutator, _1: Stmt, /) -> Stmt: ...
    def PyStmtExprVisitorDefaultVisitExpr(_0: PyStmtExprVisitor, _1: PrimExpr, /) -> None: ...
    def PyStmtExprVisitorDefaultVisitStmt(_0: PyStmtExprVisitor, _1: Stmt, /) -> None: ...
    def PyStmtExprVisitorVisitExpr(_0: PyStmtExprVisitor, _1: PrimExpr, /) -> None: ...
    def PyStmtExprVisitorVisitStmt(_0: PyStmtExprVisitor, _1: Stmt, /) -> None: ...
    def Ramp(_0: PrimExpr, _1: PrimExpr, _2: PrimExpr, _3: Span, /) -> Ramp: ...
    def Reduce(_0: CommReducer, _1: Sequence[PrimExpr], _2: Sequence[IterVar], _3: PrimExpr, _4: int, _5: Sequence[PrimExpr], _6: Span, /) -> Reduce: ...
    def RenewDefs(_0: PrimFunc, /) -> PrimFunc: ...
    def Select(_0: PrimExpr, _1: PrimExpr, _2: PrimExpr, _3: Span, /) -> Select: ...
    def SeqStmt(_0: Sequence[Stmt], _1: Span, /) -> SeqStmt: ...
    def Shuffle(_0: Sequence[PrimExpr], _1: Sequence[PrimExpr], _2: Span, /) -> Shuffle: ...
    def SizeVar(_0: str, _1: dtype, _2: Span, /) -> SizeVar: ...
    def Specialize(_0: PrimFunc, _1: Mapping[Var, Buffer | PrimExpr], /) -> PrimFunc: ...
    def StmtSRefInlineMark() -> StmtSRef: ...
    def StmtSRefParent(_0: StmtSRef, /) -> StmtSRef | None: ...
    def StmtSRefRootMark() -> StmtSRef: ...
    def StmtSRefStmt(_0: StmtSRef, /) -> Stmt | None: ...
    def StringImm(_0: str, _1: Span, /) -> StringImm: ...
    def Sub(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> Sub: ...
    def Substitute(_0: Object, _1: Mapping[Var, PrimExpr], /) -> Object: ...
    def TensorIntrin(_0: PrimFunc, _1: PrimFunc, /) -> TensorIntrin: ...
    def TensorIntrinGet(_0: str, _1: bool, /) -> TensorIntrin | None: ...
    def TensorIntrinRegister(_0: str, _1: TensorIntrin, _2: bool, /) -> None: ...
    def Var(_0: str, _1: Any, _2: Span, /) -> Var: ...
    def While(_0: PrimExpr, _1: Stmt, _2: Span, /) -> While: ...
    def _OpAdd(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpAnd(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpCeilDiv(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpDiv(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpEQ(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpFloorDiv(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpFloorMod(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpGE(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpGT(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpIfThenElse(_0: PrimExpr, _1: PrimExpr, _2: PrimExpr, _3: Span, /) -> PrimExpr: ...
    def _OpIndexDiv(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpIndexMod(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpLE(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpLT(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpLogAddExp(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpMax(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpMin(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpMod(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpMul(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpNE(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpOr(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpPow(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpSub(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpTruncDiv(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _OpTruncMod(_0: PrimExpr, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def _cast(_0: dtype, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def abs(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def bitwise_and(*args: Any) -> Any: ...
    def bitwise_not(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def bitwise_or(*args: Any) -> Any: ...
    def bitwise_xor(*args: Any) -> Any: ...
    def break_loop(_0: Span, /) -> PrimExpr: ...
    def ceil(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def const_true(_0: dtype, _1: Span, /) -> PrimExpr: ...
    def continue_loop(_0: Span, /) -> PrimExpr: ...
    def convert(_0: PrimExpr | Sequence[PrimExpr], /) -> PrimExpr | Sequence[PrimExpr]: ...
    def floor(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def infinity(_0: dtype, _1: Span, /) -> PrimExpr: ...
    def isfinite(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def isinf(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def isnan(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def left_shift(*args: Any) -> Any: ...
    def likely(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def max_value(_0: dtype, _1: Span, /) -> PrimExpr: ...
    def min_value(_0: dtype, _1: Span, /) -> PrimExpr: ...
    def nearbyint(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def reinterpret(_0: dtype, _1: PrimExpr, _2: Span, /) -> PrimExpr: ...
    def ret(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def right_shift(*args: Any) -> Any: ...
    def round(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
    def thread_return(_0: Span, /) -> PrimExpr: ...
    def trunc(_0: PrimExpr, _1: Span, /) -> PrimExpr: ...
# fmt: on
# tvm-ffi-stubgen(end)
