#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

export PYTHONPATH="${PYTHONPATH:-python}"
export TVM_LIBRARY_PATH="${TVM_LIBRARY_PATH:-build}"
export TVM_RKNPU_BRIDGE_REAL_SUBMIT="${TVM_RKNPU_BRIDGE_REAL_SUBMIT:-1}"
export TVM_RKNPU_BRIDGE_USE_RELOCS="${TVM_RKNPU_BRIDGE_USE_RELOCS:-1}"
export TVM_RKNPU_BRIDGE_RUN_CPU_AFTER_SUBMIT="${TVM_RKNPU_BRIDGE_RUN_CPU_AFTER_SUBMIT:-0}"
export TVM_RKNPU_BRIDGE_FAIL_ON_FALLBACK="${TVM_RKNPU_BRIDGE_FAIL_ON_FALLBACK:-1}"
export TVM_RKNPU_BRIDGE_VALIDATE_RELOCS="${TVM_RKNPU_BRIDGE_VALIDATE_RELOCS:-1}"

MS="${TVM_RKNPU_MLP_MVP_MS:-1,15,16,63,64,65,127,128,129,257,511,512,1024,1500}"
D_MODEL="${TVM_RKNPU_MLP_MVP_D_MODEL:-64}"
HIDDEN="${TVM_RKNPU_MLP_MVP_HIDDEN:-256}"
WARMUP="${TVM_RKNPU_MLP_MVP_WARMUP:-1}"
ITERS="${TVM_RKNPU_MLP_MVP_ITERS:-3}"
SEED="${TVM_RKNPU_MLP_MVP_SEED:-0}"

MAX_ERR="${TVM_RKNPU_MLP_MVP_MAX_ERR:-0.01}"
MAX_NON_FINITE="${TVM_RKNPU_MLP_MVP_MAX_NON_FINITE:-0}"
EXPECTED_STAGE_IDS="${TVM_RKNPU_MLP_MVP_EXPECTED_STAGE_IDS:-6,11,2}"
EXPECTED_NUM_SUBMITS="${TVM_RKNPU_MLP_MVP_EXPECTED_NUM_SUBMITS:-1}"
EXPECTED_BLOCKED_BOUNDARIES="${TVM_RKNPU_MLP_MVP_EXPECTED_BLOCKED_BOUNDARIES:-0}"

echo "[RKNPU mlp-mvp gate] running residual-MLP sweep"
python3 tools/rknpu_mlp_mvp_sweep.py \
  --ms "${MS}" \
  --d-model "${D_MODEL}" \
  --hidden "${HIDDEN}" \
  --warmup "${WARMUP}" \
  --iters "${ITERS}" \
  --seed "${SEED}" \
  --max-err "${MAX_ERR}" \
  --max-non-finite "${MAX_NON_FINITE}" \
  --expected-stage-ids "${EXPECTED_STAGE_IDS}" \
  --expected-num-submits "${EXPECTED_NUM_SUBMITS}" \
  --expected-blocked-boundaries "${EXPECTED_BLOCKED_BOUNDARIES}"

echo "[RKNPU mlp-mvp gate] PASS"
