# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""FFI APIs for tvm.tir.transform"""
# tvm-ffi-stubgen(begin): import-section
# fmt: off
# isort: off
from __future__ import annotations
from tvm_ffi import init_ffi_api as _FFI_INIT_FUNC
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from collections.abc import Mapping
    from ir import IRModule, PrimExpr
    from target import Target
    from tir import IterVar, PrimFunc, PrimFuncPass
    from transform import Pass, PassContext, PassInfo
    from typing import Callable
# isort: on
# fmt: on
# tvm-ffi-stubgen(end)



# tvm-ffi-stubgen(begin): global/tir.transform
# fmt: off
_FFI_INIT_FUNC("tir.transform", __name__)
if TYPE_CHECKING:
    def AnnotateDeviceRegions() -> Pass: ...
    def AnnotateEntryFunc() -> Pass: ...
    def AnnotateIrregularLoop() -> Pass: ...
    def BF16ComputeLegalize() -> Pass: ...
    def BF16StorageLegalize() -> Pass: ...
    def BindTarget(_0: Target, /) -> Pass: ...
    def CanonicalizeLoop() -> Pass: ...
    def CombineContextCall() -> Pass: ...
    def CommonSubexprElimTIR(_0: bool, _1: bool, /) -> Pass: ...
    def CompactBufferAllocation(_0: bool, /) -> Pass: ...
    def ConvertBlocksToOpaque() -> Pass: ...
    def ConvertForLoopsToSerial() -> Pass: ...
    def ConvertSSA() -> Pass: ...
    def CreatePrimFuncPass(_0: Callable[[ObjectRValueRef[PrimFunc], IRModule, PassContext], PrimFunc], _1: PassInfo, /) -> PrimFuncPass: ...
    def DecorateDeviceScope() -> Pass: ...
    def DefaultGPUSchedule() -> Pass: ...
    def ExtractPrimFuncConstants() -> Pass: ...
    def FP8ComputeLegalize(_0: str, /) -> Pass: ...
    def FP8StorageLegalize() -> Pass: ...
    def Filter(_0: Callable[[PrimFunc], bool], /) -> Pass: ...
    def FlattenBuffer() -> Pass: ...
    def ForceNarrowIndexToInt32() -> Pass: ...
    def HoistExpression() -> Pass: ...
    def HoistIfThenElse() -> Pass: ...
    def HoistIfThenElseBasic() -> Pass: ...
    def InferFragment() -> Pass: ...
    def InjectDoubleBuffer() -> Pass: ...
    def InjectPTXAsyncCopy() -> Pass: ...
    def InjectPTXLDG32(_0: bool, /) -> Pass: ...
    def InjectPermutedLayout() -> Pass: ...
    def InjectRollingBuffer() -> Pass: ...
    def InjectSoftwarePipeline() -> Pass: ...
    def InjectVirtualThread() -> Pass: ...
    def InlinePrivateFunctions() -> Pass: ...
    def InstrumentBoundCheckers() -> Pass: ...
    def InstrumentProfileIntrinsics() -> Pass: ...
    def LiftThreadBinding() -> Pass: ...
    def LoopPartition() -> Pass: ...
    def LowerAsyncDMA() -> Pass: ...
    def LowerAutoCopy() -> Pass: ...
    def LowerCrossThreadReduction() -> Pass: ...
    def LowerCustomDatatypes() -> Pass: ...
    def LowerDeviceKernelLaunch() -> Pass: ...
    def LowerDeviceStorageAccessInfo() -> Pass: ...
    def LowerInitBlock() -> Pass: ...
    def LowerIntrin() -> Pass: ...
    def LowerMatchBuffer() -> Pass: ...
    def LowerOpaqueBlock() -> Pass: ...
    def LowerTVMBuiltin() -> Pass: ...
    def LowerThreadAllreduce() -> Pass: ...
    def LowerVtcmAlloc() -> Pass: ...
    def LowerWarpMemory() -> Pass: ...
    def MakePackedAPI() -> Pass: ...
    def MakeUnpackedAPI() -> Pass: ...
    def ManifestSharedMemoryLocalStage() -> Pass: ...
    def MergeSharedMemoryAllocations() -> Pass: ...
    def NarrowDataType(_0: int, /) -> Pass: ...
    def PlanAndUpdateBufferAllocationLocation() -> Pass: ...
    def PointerValueTypeRewrite() -> Pass: ...
    def ReduceBranchingThroughOvercompute() -> Pass: ...
    def RemapThreadAxis(_0: Mapping[str, IterVar], /) -> Pass: ...
    def RemoveAssume() -> Pass: ...
    def RemoveNoOp() -> Pass: ...
    def RemoveStoreUndef() -> Pass: ...
    def RemoveWeightLayoutRewriteBlock(_0: bool, /) -> Pass: ...
    def RenormalizeSplitPattern() -> Pass: ...
    def RewriteUnsafeSelect() -> Pass: ...
    def Simplify() -> Pass: ...
    def SkipAssert() -> Pass: ...
    def SplitHostDevice() -> Pass: ...
    def StorageRewrite() -> Pass: ...
    def ThreadSync(_0: str, /) -> Pass: ...
    def TransformMmaBufferLayout() -> Pass: ...
    def UnifyThreadBinding() -> Pass: ...
    def UnrollLoop() -> Pass: ...
    def UseAssumeToReduceBranches() -> Pass: ...
    def VectorizeLoop(_0: bool, /) -> Pass: ...
    def VerifyGPUCode(_0: Mapping[str, PrimExpr], /) -> Pass: ...
    def VerifyMemory() -> Pass: ...
    def VerifySSA() -> Pass: ...
    def VerifyVTCMLimit(_0: Target | None, /) -> Pass: ...
# fmt: on
# tvm-ffi-stubgen(end)
