# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Constructor APIs"""
# tvm-ffi-stubgen(begin): import-section
# fmt: off
# isort: off
from __future__ import annotations
from tvm_ffi import init_ffi_api as _FFI_INIT_FUNC
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from collections.abc import Sequence
    from ir import FloatImm, IntImm, RelaxExpr
    from tvm_ffi import dtype
# isort: on
# fmt: on
# tvm-ffi-stubgen(end)


# tvm-ffi-stubgen(begin): global/relax.op.nn
# fmt: off
_FFI_INIT_FUNC("relax.op.nn", __name__)
if TYPE_CHECKING:
    def adaptive_avg_pool1d(_0: RelaxExpr, _1: Sequence[IntImm] | None, _2: str, _3: str | None, /) -> RelaxExpr: ...
    def adaptive_avg_pool2d(_0: RelaxExpr, _1: Sequence[IntImm] | None, _2: str, _3: str | None, /) -> RelaxExpr: ...
    def adaptive_avg_pool3d(_0: RelaxExpr, _1: Sequence[IntImm] | None, _2: str, _3: str | None, /) -> RelaxExpr: ...
    def attention(_0: RelaxExpr, _1: RelaxExpr, _2: RelaxExpr, _3: RelaxExpr | None, _4: FloatImm | None, _5: str | None, _6: IntImm | None, /) -> RelaxExpr: ...
    def attention_var_len(_0: RelaxExpr, _1: RelaxExpr, _2: RelaxExpr, _3: RelaxExpr, _4: RelaxExpr, _5: RelaxExpr, _6: RelaxExpr, _7: FloatImm | None, _8: str | None, _9: IntImm | None, /) -> RelaxExpr: ...
    def avg_pool1d(_0: RelaxExpr, _1: Sequence[IntImm], _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: bool, _6: bool, _7: str, _8: str | None, /) -> RelaxExpr: ...
    def avg_pool2d(_0: RelaxExpr, _1: Sequence[IntImm], _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: bool, _6: bool, _7: str, _8: str | None, /) -> RelaxExpr: ...
    def avg_pool3d(_0: RelaxExpr, _1: Sequence[IntImm], _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: bool, _6: bool, _7: str, _8: str | None, /) -> RelaxExpr: ...
    def batch_norm(_0: RelaxExpr, _1: RelaxExpr, _2: RelaxExpr, _3: RelaxExpr, _4: RelaxExpr, _5: int, _6: float, _7: bool, _8: bool, _9: float, _10: bool, /) -> RelaxExpr: ...
    def conv1d(_0: RelaxExpr, _1: RelaxExpr, _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: int, _6: str, _7: str, _8: str | None, _9: dtype | None, /) -> RelaxExpr: ...
    def conv1d_transpose(_0: RelaxExpr, _1: RelaxExpr, _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: Sequence[IntImm], _6: int, _7: str, _8: str, _9: str | None, _10: dtype | None, /) -> RelaxExpr: ...
    def conv2d(_0: RelaxExpr, _1: RelaxExpr, _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: int, _6: str, _7: str, _8: str | None, _9: dtype | None, /) -> RelaxExpr: ...
    def conv2d_transpose(_0: RelaxExpr, _1: RelaxExpr, _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: Sequence[IntImm], _6: int, _7: str, _8: str, _9: str | None, _10: dtype | None, /) -> RelaxExpr: ...
    def conv3d(_0: RelaxExpr, _1: RelaxExpr, _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: int, _6: str, _7: str, _8: str | None, _9: dtype | None, /) -> RelaxExpr: ...
    def cross_entropy_with_logits(_0: RelaxExpr, _1: RelaxExpr, /) -> RelaxExpr: ...
    def dropout(_0: RelaxExpr, _1: float, /) -> RelaxExpr: ...
    def gelu(_0: RelaxExpr, /) -> RelaxExpr: ...
    def gelu_tanh(_0: RelaxExpr, /) -> RelaxExpr: ...
    def group_norm(_0: RelaxExpr, _1: RelaxExpr, _2: RelaxExpr, _3: int, _4: int, _5: Sequence[IntImm], _6: float, _7: bool, _8: bool, /) -> RelaxExpr: ...
    def instance_norm(_0: RelaxExpr, _1: RelaxExpr, _2: RelaxExpr, _3: int, _4: Sequence[IntImm], _5: float, _6: bool, _7: bool, /) -> RelaxExpr: ...
    def layer_norm(_0: RelaxExpr, _1: RelaxExpr, _2: RelaxExpr, _3: Sequence[IntImm], _4: float, _5: bool, _6: bool, /) -> RelaxExpr: ...
    def leakyrelu(_0: RelaxExpr, _1: float, /) -> RelaxExpr: ...
    def log_softmax(_0: RelaxExpr, _1: int, /) -> RelaxExpr: ...
    def max_pool1d(_0: RelaxExpr, _1: Sequence[IntImm], _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: bool, _6: bool, _7: str, _8: str | None, /) -> RelaxExpr: ...
    def max_pool2d(_0: RelaxExpr, _1: Sequence[IntImm], _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: bool, _6: bool, _7: str, _8: str | None, /) -> RelaxExpr: ...
    def max_pool3d(_0: RelaxExpr, _1: Sequence[IntImm], _2: Sequence[IntImm], _3: Sequence[IntImm], _4: Sequence[IntImm], _5: bool, _6: bool, _7: str, _8: str | None, /) -> RelaxExpr: ...
    def nll_loss(_0: RelaxExpr, _1: RelaxExpr, _2: RelaxExpr | None, _3: str, _4: int, /) -> RelaxExpr: ...
    def pad(_0: RelaxExpr, _1: Sequence[IntImm], _2: str, _3: float, /) -> RelaxExpr: ...
    def pixel_shuffle(_0: RelaxExpr, _1: int, /) -> RelaxExpr: ...
    def prelu(_0: RelaxExpr, _1: RelaxExpr, _2: int, /) -> RelaxExpr: ...
    def relu(_0: RelaxExpr, /) -> RelaxExpr: ...
    def rms_norm(_0: RelaxExpr, _1: RelaxExpr, _2: Sequence[IntImm], _3: float, /) -> RelaxExpr: ...
    def selu(_0: RelaxExpr, /) -> RelaxExpr: ...
    def silu(_0: RelaxExpr, /) -> RelaxExpr: ...
    def softmax(_0: RelaxExpr, _1: int, /) -> RelaxExpr: ...
    def softplus(_0: RelaxExpr, _1: float, _2: float, /) -> RelaxExpr: ...
# fmt: on
# tvm-ffi-stubgen(end)
