# TCL File Generated by Component Editor 18.0
# Fri Dec 07 14:56:05 HKT 2018
# DO NOT MODIFY


# 
# st_dwidth_adaptor "st_dwidth_adaptor" v1.0
#  2018.12.07.14:56:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module st_dwidth_adaptor
# 
set_module_property DESCRIPTION ""
set_module_property NAME st_dwidth_adaptor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME st_dwidth_adaptor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL st_dwidth_adaptor
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file st_dwidth_adaptor.v VERILOG PATH st_dwidth_adaptor.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL st_dwidth_adaptor
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file st_dwidth_adaptor_tb.v VERILOG PATH st_dwidth_adaptor_tb.v


# 
# parameters
# 
add_parameter INPUT_WIDTH INTEGER 128
set_parameter_property INPUT_WIDTH DEFAULT_VALUE 128
set_parameter_property INPUT_WIDTH DISPLAY_NAME INPUT_WIDTH
set_parameter_property INPUT_WIDTH TYPE INTEGER
set_parameter_property INPUT_WIDTH UNITS None
set_parameter_property INPUT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property INPUT_WIDTH HDL_PARAMETER true
add_parameter OUTPUT_WIDTH INTEGER 512
set_parameter_property OUTPUT_WIDTH DEFAULT_VALUE 512
set_parameter_property OUTPUT_WIDTH DISPLAY_NAME OUTPUT_WIDTH
set_parameter_property OUTPUT_WIDTH TYPE INTEGER
set_parameter_property OUTPUT_WIDTH UNITS None
set_parameter_property OUTPUT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property OUTPUT_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point snk
# 
add_interface snk avalon_streaming end
set_interface_property snk associatedClock clock
set_interface_property snk associatedReset reset
set_interface_property snk dataBitsPerSymbol 8
set_interface_property snk errorDescriptor ""
set_interface_property snk firstSymbolInHighOrderBits true
set_interface_property snk maxChannel 0
set_interface_property snk readyLatency 0
set_interface_property snk ENABLED true
set_interface_property snk EXPORT_OF ""
set_interface_property snk PORT_NAME_MAP ""
set_interface_property snk CMSIS_SVD_VARIABLES ""
set_interface_property snk SVD_ADDRESS_GROUP ""

add_interface_port snk snk_data data Input INPUT_WIDTH
add_interface_port snk snk_ready ready Output 1
add_interface_port snk snk_valid valid Input 1


# 
# connection point src
# 
add_interface src avalon_streaming start
set_interface_property src associatedClock clock
set_interface_property src associatedReset reset
set_interface_property src dataBitsPerSymbol 8
set_interface_property src errorDescriptor ""
set_interface_property src firstSymbolInHighOrderBits true
set_interface_property src maxChannel 0
set_interface_property src readyLatency 0
set_interface_property src ENABLED true
set_interface_property src EXPORT_OF ""
set_interface_property src PORT_NAME_MAP ""
set_interface_property src CMSIS_SVD_VARIABLES ""
set_interface_property src SVD_ADDRESS_GROUP ""

add_interface_port src src_data data Output OUTPUT_WIDTH
add_interface_port src src_ready ready Input 1
add_interface_port src src_valid valid Output 1

