# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Generate CUDA configuration APIs, native encoders, and documentation.

Run this file directly, without importing TVM. ``--check`` verifies checked-in
outputs without changing files; compiler builds do not execute this generator.
"""

# ruff: noqa: E501

import argparse
import importlib.util
import subprocess
import sys
from pathlib import Path

DIRECTORY = Path(__file__).resolve().parent
ROOT = DIRECTORY.parents[4]
spec = importlib.util.spec_from_file_location("_cuda_launch_table", DIRECTORY / "table.py")
table = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = table
spec.loader.exec_module(table)
PY_LICENSE = (DIRECTORY / "table.py").read_text().split('"""', 1)[0]
CPP_LICENSE = "/*\n" + "\n".join(" *" + line[1:] for line in PY_LICENSE.splitlines()) + "\n */\n"


def camel(name):
    return "".join(word.title() for word in name.replace(".", "_").split("_"))


def leaf_name(field, member):
    return field.name + ("." + member if member else "")


def leaf_id(field, member=""):
    return "k" + camel(leaf_name(field, member))


def python_api():
    out = [
        PY_LICENSE,
        '"""Generated by launch/generate.py; edit table.py instead."""\n',
        "from dataclasses import dataclass\nfrom typing import Any, ClassVar\n",
        "from ._impl import Config\n",
    ]
    classes = [
        *table.COMPOSITES.items(),
        ("LaunchConfig", table.LAUNCH_FIELDS),
        ("KernelOptions", table.KERNEL_FIELDS),
    ]
    for name, fields in classes:
        out += [
            "\n@dataclass(frozen=True, kw_only=True)",
            f"class {name}(Config):",
            f'    """CUDA {name} configuration. See the generated launch reference."""',
            f'    _config_type: ClassVar[str] = "{name}"',
        ]
        for field in fields:
            default = "" if field.default == "required" else " = " + field.default
            out += [f"    {field.name}: Any{default}"]
        out += [""]
    out += ["__all__ = " + repr([name for name, _ in classes])]
    return "\n".join(out) + "\n"


def native_fields():
    leaves = list(table.leaves())
    out = [
        CPP_LICENSE,
        "// Generated by launch/generate.py; edit table.py instead.",
        "#ifndef TVM_BACKEND_CUDA_LAUNCH_LAUNCH_FIELDS_H_",
        "#define TVM_BACKEND_CUDA_LAUNCH_LAUNCH_FIELDS_H_",
        "#include <array>\n#include <cstdint>\n#include <stdexcept>\n#include <string>",
        "namespace tvm_cuda_launch {",
        "enum class ValueKind { kInteger, kFloat, kHandle };",
        "enum class Option {",
    ]
    out += [f"  k{camel(field.name)}," for field in table.LAUNCH_FIELDS]
    out += ["  kCount\n};", "enum class Field {"]
    out += [f"  {leaf_id(field, member)}," for field, member, _ in leaves]
    out += [
        "  kCount\n};",
        "struct FieldInfo { const char* name; Option option; ValueKind kind; };",
        "inline constexpr std::array<FieldInfo, static_cast<size_t>(Field::kCount)> kFields{{",
    ]
    for field, member, kind in leaves:
        value_kind = {"handle": "Handle", "float": "Float"}.get(kind, "Integer")
        out += [
            f'  {{"{leaf_name(field, member)}", Option::k{camel(field.name)}, ValueKind::k{value_kind}}},'
        ]
    out += [
        "}};",
        "inline Field FindField(const std::string& name) {",
        "  for (size_t i = 0; i < kFields.size(); ++i) if (name == kFields[i].name) return static_cast<Field>(i);",
        '  throw std::invalid_argument("Unknown CUDA launch field: " + name);',
        "}",
        "struct KernelRequirements { bool required_block_size = false; std::array<int64_t, 3> block{}; std::array<int64_t, 3> cluster{}; };",
        "struct Value { int64_t integer = 0; double real = 0; void* handle = nullptr; };",
        "struct LaunchValues {",
        "  std::array<Value, static_cast<size_t>(Field::kCount)> values{};",
        "  std::array<bool, static_cast<size_t>(Option::kCount)> present{};",
        "  LaunchValues() {",
    ]
    for field, member, _ in leaves:
        if field.kind == "dim3":
            out += [
                f"    values[static_cast<size_t>(Field::{leaf_id(field, member)})].integer = 1;"
            ]
    out += [
        "  }",
        "  bool Has(Option option) const { return present[static_cast<size_t>(option)]; }",
        "  const Value& Get(Field field) const { return values[static_cast<size_t>(field)]; }",
        "  int64_t Int(Field field) const { return Get(field).integer; }",
        "  void Set(Field field, Value value) {",
        "    size_t index = static_cast<size_t>(field); values[index] = value;",
        "    present[static_cast<size_t>(kFields[index].option)] = true;",
        "  }",
        "  void SetInt(Field field, int64_t value) { Value v; v.integer = value; Set(field, v); }",
        "  void SetFloat(Field field, double value) { Value v; v.real = value; Set(field, v); }",
        "  void SetHandle(Field field, void* value) { Value v; v.handle = value; Set(field, v); }",
        "};",
        "inline void NormalizeLegacyPresence(LaunchValues* values) {",
        "  for (size_t i = 0; i < static_cast<size_t>(Field::kDynamicSmemBytes); ++i)",
        "    if (values->values[i].integer == 0) values->values[i].integer = 1;",
        "  if (values->Int(Field::kPreferredClusterX) == 1 && values->Int(Field::kPreferredClusterY) == 1 && values->Int(Field::kPreferredClusterZ) == 1)",
        "    values->present[static_cast<size_t>(Option::kPreferredCluster)] = false;",
        "}",
        "}  // namespace tvm_cuda_launch",
        "#endif",
        "",
    ]
    return "\n".join(out)


def native_attributes():
    out = [
        CPP_LICENSE,
        "// Generated by launch/generate.py; edit table.py instead.",
        "#ifndef TVM_BACKEND_CUDA_LAUNCH_LAUNCH_ATTRIBUTES_H_",
        "#define TVM_BACKEND_CUDA_LAUNCH_LAUNCH_ATTRIBUTES_H_",
        '#include "launch_fields.h"',
        "#include <cuda.h>\n#include <cuda_runtime.h>",
        "namespace tvm_cuda_launch {",
        f"inline constexpr size_t kMaxAttributes = {len(table.LAUNCH_FIELDS)};",
    ]
    for api, native_type, prefix, union, version in (
        ("Driver", "CUlaunchAttribute", "CU_LAUNCH_ATTRIBUTE_", "value", "CUDA_VERSION"),
        ("Runtime", "cudaLaunchAttribute", "cudaLaunchAttribute", "val", "CUDART_VERSION"),
    ):
        out += [
            f"inline unsigned Encode{api}Attributes(const LaunchValues& config,",
            f"    std::array<{native_type}, kMaxAttributes>* attrs, bool required_block_size) {{",
            "  unsigned count = 0;",
        ]
        for field in table.LAUNCH_FIELDS:
            if not field.driver_id:
                continue
            condition = f"config.Has(Option::k{camel(field.name)})"
            if field.name in ("cluster", "preferred_cluster"):
                condition += " && !required_block_size"
            out += [
                f"  if ({condition}) {{",
                f"#if {version} >= {field.version}",
                "    auto& attr = (*attrs)[count++];",
                f"    attr.id = {prefix}{field.driver_id if api == 'Driver' else field.runtime_id};",
            ]
            if field.kind == "dim3":
                members = [(axis, axis, "int") for axis in "xyz"]
            elif field.kind in table.COMPOSITES:
                member_types = {x.name: x.kind for x in table.COMPOSITES[field.kind]}
                members = [
                    (member, native, member_types[member]) for member, native in field.members
                ]
            else:
                members = [("", "", field.kind)]
            for member, native_member, kind in members:
                native = f"attr.{union}.{field.native_member}" + (
                    "." + native_member if native_member else ""
                )
                value = {"handle": "handle", "float": "real"}.get(kind, "integer")
                out += [
                    f"    {native} = static_cast<decltype({native})>(config.Get(Field::{leaf_id(field, member)}).{value});"
                ]
            if field.name == "shared_memory_mode":
                out += [
                    f"#if {version} < 13040",
                    "    if (config.Int(Field::kSharedMemoryMode) > 2)",
                    '      throw std::invalid_argument("CUDA oversized shared memory requires CUDA 13.4 or newer");',
                    "#endif",
                ]
            out += [
                "#else",
                f'    throw std::invalid_argument("CUDA launch field {field.name} requires toolkit {field.version // 1000}.{field.version % 1000 // 10} or newer");',
                "#endif",
                "  }",
            ]
        out += ["  return count;", "}"]
    out += ["}  // namespace tvm_cuda_launch", "#endif", ""]
    return "\n".join(out)


def documentation():
    out = [
        ".. Licensed to the Apache Software Foundation (ASF) under one",
        "   or more contributor license agreements. See the NOTICE file",
        "   distributed with this work for additional information",
        "   regarding copyright ownership. The ASF licenses this file",
        '   to you under the Apache License, Version 2.0 (the "License");',
        "   you may not use this file except in compliance with the License.",
        "   You may obtain a copy of the License at",
        "",
        "   http://www.apache.org/licenses/LICENSE-2.0",
        "",
        "   Unless required by applicable law or agreed to in writing,",
        '   software distributed under the License is distributed on an "AS IS" BASIS,',
        "   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
        "   See the License for the specific language governing permissions and",
        "   limitations under the License.",
        "",
        ".. Generated by launch/generate.py; edit table.py instead.",
        "",
        "CUDA kernel configuration reference",
        "===================================",
        "",
        "Both CUDA module launches and exported ``cuda_host`` wrappers use this registry.",
        "Optional launch attributes default to unspecified, preserving CUDA's inherited defaults.",
        "",
    ]
    for name, fields in [
        ("LaunchConfig", table.LAUNCH_FIELDS),
        ("KernelOptions", table.KERNEL_FIELDS),
        *table.COMPOSITES.items(),
    ]:
        out += [
            name,
            "-" * len(name),
            "",
            ".. list-table::",
            "   :header-rows: 1",
            "",
            "   * - Field",
            "     - Type",
            "     - Default",
            "     - Description",
        ]
        for field in fields:
            doc = field.doc
            if field.enums:
                doc += " Values: " + ", ".join(f"``{key}``" for key, _ in field.enums) + "."
            if field.driver_id:
                doc += (
                    f" Encoder requires CUDA {field.version // 1000}.{field.version % 1000 // 10}+."
                )
            out += [
                f"   * - ``{field.name}``",
                f"     - {field.kind}",
                f"     - ``{field.default}``",
                f"     - {doc}",
            ]
        out += [""]
    out += [
        "Stream-only synchronization policy and graph-only device-updatable nodes are",
        "outside this kernel-launch API. CUDA checks device-specific support and resource limits.",
        "",
    ]
    return "\n".join(out)


def format_output(path, content):
    """Use the same pinned formatters as pre-commit, without importing TVM."""
    if path.suffix == ".py":
        for command in (
            ["ruff", "format", "--stdin-filename", str(path), "-"],
            ["ruff", "check", "--fix", "--stdin-filename", str(path), "-"],
            ["ruff", "format", "--stdin-filename", str(path), "-"],
        ):
            content = subprocess.run(
                command, input=content, text=True, capture_output=True, check=True, cwd=ROOT
            ).stdout
    elif path.suffix == ".h":
        content = subprocess.run(
            ["clang-format", "--assume-filename=" + str(path)],
            input=content,
            text=True,
            capture_output=True,
            check=True,
            cwd=ROOT,
        ).stdout
    return content


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {
        DIRECTORY / "_generated.py": python_api(),
        ROOT / "src/backend/cuda/launch/launch_fields.h": native_fields(),
        ROOT / "src/backend/cuda/launch/launch_attributes.h": native_attributes(),
        ROOT / "docs/tirx/api/cuda_launch.rst": documentation(),
    }
    for path in list(outputs):
        outputs[path] = format_output(path, outputs[path])
    support = "\n".join(
        [
            outputs[ROOT / "src/backend/cuda/launch/launch_fields.h"],
            outputs[ROOT / "src/backend/cuda/launch/launch_attributes.h"].replace(
                '#include "launch_fields.h"', ""
            ),
            (ROOT / "src/backend/cuda/launch/launch_config.h")
            .read_text()
            .replace('#include "launch_attributes.h"', ""),
        ]
    )
    outputs[ROOT / "src/backend/cuda/launch/launch_source.h"] = (
        CPP_LICENSE
        + "\n// Generated by launch/generate.py; edit the registry or launch_config.h.\n"
        "#ifndef TVM_BACKEND_CUDA_LAUNCH_LAUNCH_SOURCE_H_\n"
        "#define TVM_BACKEND_CUDA_LAUNCH_LAUNCH_SOURCE_H_\n"
        'namespace tvm_cuda_launch {\ninline constexpr const char* kSupportSource = R"TVM_CUDA_LAUNCH(\n'
        + support
        + '\n)TVM_CUDA_LAUNCH";\n}\n#endif\n'
    )
    source_path = ROOT / "src/backend/cuda/launch/launch_source.h"
    outputs[source_path] = format_output(source_path, outputs[source_path])
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        raise SystemExit("Stale CUDA launch generated files: " + ", ".join(stale))


if __name__ == "__main__":
    main()
