# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Checkout mainline commit on local repo and run tests.
name: Adreno Package Generation

on:
  schedule:
    # 2:30 AM IST
    - cron: "1 20 * * *"
  workflow_dispatch:

concurrency:
  group: tvmpkg
  cancel-in-progress: true

jobs:
  BuildPackageLinux:
    if: github.repository == 'gpgpu/apache-tvm'
    runs-on: blr-ubuntu-tvm01
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'recursive'
            fetch-depth: 0
      - name: Build CPU Host Wheel
        shell: bash -l {0}
        run: |
           set -e
           docker run --rm --pid=host -w /workspace \
               -v ${PWD}:/workspace \
               -v ${ADRENOACCL_SDK}:/adrenoaccl_sdk \
               -e ADRENOACCL_SDK=/adrenoaccl_sdk \
               -v ${ADRENO_OPENCL}:/adreno_opencl \
               -e ADRENO_OPENCL=/adreno_opencl \
               -e ENV_USER_ID=`id -u` \
               -e ENV_GROUP_ID=`id -g` \
               mlcaidev/package-cu121 \
               conda run -n py38 ./ci/adreno/build_lib.sh
           docker run --rm --pid=host -w /workspace \
               -v ${PWD}:/workspace \
               -v ${ADRENOACCL_SDK}:/adrenoaccl_sdk \
               -e ADRENOACCL_SDK=/adrenoaccl_sdk \
               -v ${ADRENO_OPENCL}:/adreno_opencl \
               -e ADRENO_OPENCL=/adreno_opencl \
               -e ENV_USER_ID=`id -u` \
               -e ENV_GROUP_ID=`id -g` \
               -e WHEEL_EXT_NAME="_adreno_cpu" \
               mlcaidev/package-cu121 \
               conda run -n py38 ./ci/adreno/build_wheel.sh
           mkdir -p nightly
           cp wheels/*.whl ./nightly/ -rfa
           mv wheels/*.whl ${BUILD_WHEEL_PATH}/
           docker run --rm --pid=host -w /workspace \
               -v ${PWD}:/workspace \
               -v ${ADRENOACCL_SDK}:/adrenoaccl_sdk \
               -e ADRENOACCL_SDK=/adrenoaccl_sdk \
               -v ${ADRENO_OPENCL}:/adreno_opencl \
               -e ADRENO_OPENCL=/adreno_opencl \
               -e ENV_USER_ID=`id -u` \
               -e ENV_GROUP_ID=`id -g` \
               mlcaidev/package-cu121 \
               conda run -n py38 ./ci/adreno/build_clean.sh
      - name: Build CUDA Host Wheel
        shell: bash -l {0}
        run: |
           set -e
           docker run --rm --pid=host -w /workspace \
               -v ${PWD}:/workspace \
               -v ${ADRENOACCL_SDK}:/adrenoaccl_sdk \
               -e ADRENOACCL_SDK=/adrenoaccl_sdk \
               -v ${ADRENO_OPENCL}:/adreno_opencl \
               -e ADRENO_OPENCL=/adreno_opencl \
               -e ENV_USER_ID=`id -u` \
               -e ENV_GROUP_ID=`id -g` \
               -e GPU=cuda \
               mlcaidev/package-cu121 \
               conda run -n py38 ./ci/adreno/build_lib.sh
           docker run --rm --pid=host -w /workspace \
               -v ${PWD}:/workspace \
               -v ${ADRENOACCL_SDK}:/adrenoaccl_sdk \
               -e ADRENOACCL_SDK=/adrenoaccl_sdk \
               -v ${ADRENO_OPENCL}:/adreno_opencl \
               -e ADRENO_OPENCL=/adreno_opencl \
               -e ENV_USER_ID=`id -u` \
               -e ENV_GROUP_ID=`id -g` \
               -e WHEEL_EXT_NAME="_adreno_cuda" \
               -e GPU=cuda \
               mlcaidev/package-cu121 \
               conda run -n py38 ./ci/adreno/build_wheel.sh
           cp wheels/*.whl ./nightly/ -rfa
           mv wheels/*.whl ${BUILD_WHEEL_PATH}/
           docker run --rm --pid=host -w /workspace \
               -v ${PWD}:/workspace \
               -v ${ADRENOACCL_SDK}:/adrenoaccl_sdk \
               -e ADRENOACCL_SDK=/adrenoaccl_sdk \
               -v ${ADRENO_OPENCL}:/adreno_opencl \
               -e ADRENO_OPENCL=/adreno_opencl \
               -e ENV_USER_ID=`id -u` \
               -e ENV_GROUP_ID=`id -g` \
               -e GPU=cuda \
               mlcaidev/package-cu121 \
               conda run -n py38 ./ci/adreno/build_clean.sh
      - name: Build Target
        shell: bash -l {0}
        run: |
           set -e
           mkdir -p build-adreno-target
           cd build-adreno-target
           cp ../cmake/config.cmake . -f
           echo set\(USE_CLML "${ADRENO_OPENCL}"\)  >> config.cmake
           echo set\(USE_CLML_GRAPH_EXECUTOR "${ADRENO_OPENCL}"\) >> config.cmake
           echo set\(USE_RPC ON\) >> config.cmake
           echo set\(USE_CPP_RPC ON\) >> config.cmake
           echo set\(USE_CPP_RTVM ON\) >> config.cmake
           echo set\(USE_GRAPH_EXECUTOR ON\) >> config.cmake
           echo set\(USE_LIBBACKTRACE AUTO\) >> config.cmake
           echo set\(USE_KALLOC_ALIGNMENT 32\) >> config.cmake
           echo set\(ANDROID_ABI arm64-v8a\) >> config.cmake
           echo set\(ANDROID_PLATFORM android-28\) >> config.cmake
           echo set\(MACHINE_NAME aarch64-linux-gnu\) >> config.cmake
           cmake -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK}/build/cmake/android.toolchain.cmake" \
                 -DANDROID_ABI=arm64-v8a \
                 -DANDROID_PLATFORM=android-28 \
                 -DCMAKE_SYSTEM_VERSION=1 \
                 -DCMAKE_FIND_ROOT_PATH="${ADRENO_OPENCL}" \
                 -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
                 -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
                 -DCMAKE_CXX_COMPILER="${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang++" \
                 -DCMAKE_C_COMPILER="${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang" \
                 -DMACHINE_NAME="aarch64-linux-gnu" ..
            cmake --build . --parallel $(nproc)
            cd -
      - name: Build Adreno Utils
        shell: bash -l {0}
        run: |
           set -e
           cp build-adreno-target/tvm_rpc adreno-utils/ -rfa
           cp build-adreno-target/rtvm adreno-utils/ -rfa
           cp build-adreno-target/libtvm_runtime.so adreno-utils/ -rfa
           tar jcvfp adreno-utils.tar.bz2 adreno-utils
           cp adreno-utils.tar.bz2 ./nightly/ -rfa
           gh release delete nightly --cleanup-tag --yes --repo "$GITHUB_REPOSITORY" || true
           gh release create nightly --latest --title nightly --repo "$GITHUB_REPOSITORY" --notes "TVM Nightly builds"
           gh release upload nightly ./nightly/* --clobber --repo "$GITHUB_REPOSITORY"
           git tag -f -a nightly -m "Update nightly commit id"
           git push origin -f --tags
           rm -rf nightly
           mv adreno-utils.tar.bz2 ${BUILD_WHEEL_PATH}/
  BuildPackageWindows:
    if: ${{ github.repository == 'gpgpu/apache-tvm' }}
    runs-on: tvm-windows
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ref: ''
      - name: Compile
        shell: powershell
        run: |
           Push-Location
           New-Item -ItemType Directory -Force -Path "./build"
           cd build
           cp ../cmake/config.cmake .
           Add-Content config.cmake "set(USE_OPENCL $ENV:OPENCL_SDK)"
           Add-Content config.cmake "set(USE_LLVM $ENV:LLVM_CONFIG)"
           Add-Content config.cmake "set(USE_ADRENO_ACCL $ENV:ADRENOACCL_SDK)"
           Add-Content config.cmake "set(USE_ADRENO_ACCL_GRAPH_EXECUTOR $ENV:ADRENOACCL_SDK)"
           cmake .. -G "Visual Studio 17 2022" -A x64
           cmake --build . --config Release --parallel $env:NUMBER_OF_PROCESSORS
           Pop-Location
      - name: Check Build Status
        shell: powershell
        run: |
           $env:PYTHONPATH = "$pwd\python"
           python -c "import tvm; print(tvm.__path__)"
      - name: Build Package and Publish
        shell: powershell
        run: |
           cd python
           $Env:WHEEL_EXT_NAME="_adreno_cpu"
           python.exe .\setup.py bdist_wheel --plat-name win_amd64
           try { gh release delete nightly-win --cleanup-tag --yes --repo $Env:GITHUB_REPOSITORY } catch { }
           gh release create nightly-win --latest --title nightly-win --repo $Env:GITHUB_REPOSITORY --notes "Windows nightly builds"
           foreach ($i in Get-ChildItem -Path dist) {gh release upload nightly-win .\dist\$i --clobber --repo $Env:GITHUB_REPOSITORY}
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
