
name: Merge
on:
  status:
  pull_request_review:
    types:
      - submitted
  issue_comment:

concurrency:
  group: merge-${{ github.event.pull_request.number }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  maybe-merge:
    if: github.repository == 'apache/tvm'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Merge if requested and possible
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          set -eux
          python tests/scripts/github_mergebot.py --pr "$PR_NUMBER" --run-url "$RUN_URL"
