
name: tests-bot
on:
  status
jobs:
  run-tests-bot:
    if: ${{ github.repository == 'apache/tvm' && github.event.state == 'success' && github.event.context == 'tvm-ci/pr-head' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment skipped tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_RESOURCES_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_RESOURCES_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
          COMMIT_SHA: ${{ github.event.sha }}
          TARGET_URL: ${{ github.event.target_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          python ci/scripts/github_skipped_tests_comment.py